/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseInfiniteQuery,
  useSuspenseQuery,
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import type {
  AnimalControllerAll200,
  AnimalControllerAllParams,
  AnimalControllerUploadBody,
  AnimalCreateRequest,
  AnimalResponse,
  AnimalUpdateRequest,
  FileResponse,
} from './index.schemas';

export type animalControllerAllResponse200 = {
  data: AnimalControllerAll200;
  status: 200;
};

export type animalControllerAllResponseSuccess = animalControllerAllResponse200 & {
  headers: Headers;
};
export const getAnimalControllerAllUrl = (params?: AnimalControllerAllParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://localhost:4000/api/v1/animals?${stringifiedParams}`
    : `http://localhost:4000/api/v1/animals`;
};

export const animalControllerAll = async (
  params?: AnimalControllerAllParams,
  options?: RequestInit,
): Promise<animalControllerAllResponseSuccess> => {
  const res = await fetch(getAnimalControllerAllUrl(params), {
    credentials: 'include',
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: animalControllerAllResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as animalControllerAllResponseSuccess;
};

export const getAnimalControllerAllInfiniteQueryKey = (params?: AnimalControllerAllParams) => {
  return ['infinite', `http://localhost:4000/api/v1/animals`, ...(params ? [params] : [])] as const;
};

export const getAnimalControllerAllQueryKey = (params?: AnimalControllerAllParams) => {
  return [`http://localhost:4000/api/v1/animals`, ...(params ? [params] : [])] as const;
};

export const getAnimalControllerAllInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerAll>>, AnimalControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof animalControllerAll>>,
        TError,
        TData,
        QueryKey,
        AnimalControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAnimalControllerAllInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof animalControllerAll>>,
    QueryKey,
    AnimalControllerAllParams['cursor']
  > = ({ signal, pageParam }) =>
    animalControllerAll({ ...params, cursor: pageParam || params?.['cursor'] }, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof animalControllerAll>>,
    TError,
    TData,
    QueryKey,
    AnimalControllerAllParams['cursor']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AnimalControllerAllInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof animalControllerAll>>>;
export type AnimalControllerAllInfiniteQueryError = unknown;

export function useAnimalControllerAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerAll>>, AnimalControllerAllParams['cursor']>,
  TError = unknown,
>(
  params: undefined | AnimalControllerAllParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof animalControllerAll>>,
        TError,
        TData,
        QueryKey,
        AnimalControllerAllParams['cursor']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof animalControllerAll>>,
          TError,
          Awaited<ReturnType<typeof animalControllerAll>>,
          QueryKey
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAnimalControllerAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerAll>>, AnimalControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof animalControllerAll>>,
        TError,
        TData,
        QueryKey,
        AnimalControllerAllParams['cursor']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof animalControllerAll>>,
          TError,
          Awaited<ReturnType<typeof animalControllerAll>>,
          QueryKey
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAnimalControllerAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerAll>>, AnimalControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof animalControllerAll>>,
        TError,
        TData,
        QueryKey,
        AnimalControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAnimalControllerAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerAll>>, AnimalControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof animalControllerAll>>,
        TError,
        TData,
        QueryKey,
        AnimalControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAnimalControllerAllInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchAnimalControllerAllInfiniteQuery = async <
  TData = Awaited<ReturnType<typeof animalControllerAll>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof animalControllerAll>>,
        TError,
        TData,
        QueryKey,
        AnimalControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getAnimalControllerAllInfiniteQueryOptions(params, options);

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
};

export const getAnimalControllerAllQueryOptions = <
  TData = Awaited<ReturnType<typeof animalControllerAll>>,
  TError = unknown,
>(
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof animalControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAnimalControllerAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof animalControllerAll>>> = ({ signal }) =>
    animalControllerAll(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof animalControllerAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AnimalControllerAllQueryResult = NonNullable<Awaited<ReturnType<typeof animalControllerAll>>>;
export type AnimalControllerAllQueryError = unknown;

export function useAnimalControllerAll<TData = Awaited<ReturnType<typeof animalControllerAll>>, TError = unknown>(
  params: undefined | AnimalControllerAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof animalControllerAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof animalControllerAll>>,
          TError,
          Awaited<ReturnType<typeof animalControllerAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAnimalControllerAll<TData = Awaited<ReturnType<typeof animalControllerAll>>, TError = unknown>(
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof animalControllerAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof animalControllerAll>>,
          TError,
          Awaited<ReturnType<typeof animalControllerAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAnimalControllerAll<TData = Awaited<ReturnType<typeof animalControllerAll>>, TError = unknown>(
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof animalControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAnimalControllerAll<TData = Awaited<ReturnType<typeof animalControllerAll>>, TError = unknown>(
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof animalControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAnimalControllerAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchAnimalControllerAllQuery = async <
  TData = Awaited<ReturnType<typeof animalControllerAll>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof animalControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getAnimalControllerAllQueryOptions(params, options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getAnimalControllerAllSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof animalControllerAll>>,
  TError = unknown,
>(
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof animalControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAnimalControllerAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof animalControllerAll>>> = ({ signal }) =>
    animalControllerAll(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof animalControllerAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AnimalControllerAllSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof animalControllerAll>>>;
export type AnimalControllerAllSuspenseQueryError = unknown;

export function useAnimalControllerAllSuspense<
  TData = Awaited<ReturnType<typeof animalControllerAll>>,
  TError = unknown,
>(
  params: undefined | AnimalControllerAllParams,
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof animalControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAnimalControllerAllSuspense<
  TData = Awaited<ReturnType<typeof animalControllerAll>>,
  TError = unknown,
>(
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof animalControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAnimalControllerAllSuspense<
  TData = Awaited<ReturnType<typeof animalControllerAll>>,
  TError = unknown,
>(
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof animalControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAnimalControllerAllSuspense<
  TData = Awaited<ReturnType<typeof animalControllerAll>>,
  TError = unknown,
>(
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof animalControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAnimalControllerAllSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getAnimalControllerAllSuspenseInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerAll>>, AnimalControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof animalControllerAll>>,
        TError,
        TData,
        QueryKey,
        AnimalControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAnimalControllerAllInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof animalControllerAll>>,
    QueryKey,
    AnimalControllerAllParams['cursor']
  > = ({ signal, pageParam }) =>
    animalControllerAll({ ...params, cursor: pageParam || params?.['cursor'] }, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseInfiniteQueryOptions<
    Awaited<ReturnType<typeof animalControllerAll>>,
    TError,
    TData,
    QueryKey,
    AnimalControllerAllParams['cursor']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AnimalControllerAllSuspenseInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof animalControllerAll>>
>;
export type AnimalControllerAllSuspenseInfiniteQueryError = unknown;

export function useAnimalControllerAllSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerAll>>, AnimalControllerAllParams['cursor']>,
  TError = unknown,
>(
  params: undefined | AnimalControllerAllParams,
  options: {
    query: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof animalControllerAll>>,
        TError,
        TData,
        QueryKey,
        AnimalControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAnimalControllerAllSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerAll>>, AnimalControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof animalControllerAll>>,
        TError,
        TData,
        QueryKey,
        AnimalControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAnimalControllerAllSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerAll>>, AnimalControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof animalControllerAll>>,
        TError,
        TData,
        QueryKey,
        AnimalControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAnimalControllerAllSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerAll>>, AnimalControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: AnimalControllerAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof animalControllerAll>>,
        TError,
        TData,
        QueryKey,
        AnimalControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAnimalControllerAllSuspenseInfiniteQueryOptions(params, options);

  const query = useSuspenseInfiniteQuery(queryOptions, queryClient) as UseSuspenseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type animalControllerCreateResponse201 = {
  data: AnimalResponse;
  status: 201;
};

export type animalControllerCreateResponseSuccess = animalControllerCreateResponse201 & {
  headers: Headers;
};
export const getAnimalControllerCreateUrl = () => {
  return `http://localhost:4000/api/v1/animals`;
};

export const animalControllerCreate = async (
  animalCreateRequest: AnimalCreateRequest,
  options?: RequestInit,
): Promise<animalControllerCreateResponseSuccess> => {
  const res = await fetch(getAnimalControllerCreateUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(animalCreateRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: animalControllerCreateResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as animalControllerCreateResponseSuccess;
};

export const getAnimalControllerCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof animalControllerCreate>>,
    TError,
    { data: AnimalCreateRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof animalControllerCreate>>,
  TError,
  { data: AnimalCreateRequest },
  TContext
> => {
  const mutationKey = ['animalControllerCreate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof animalControllerCreate>>,
    { data: AnimalCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return animalControllerCreate(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AnimalControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof animalControllerCreate>>>;
export type AnimalControllerCreateMutationBody = AnimalCreateRequest;
export type AnimalControllerCreateMutationError = unknown;

export const useAnimalControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof animalControllerCreate>>,
      TError,
      { data: AnimalCreateRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof animalControllerCreate>>,
  TError,
  { data: AnimalCreateRequest },
  TContext
> => {
  const mutationOptions = getAnimalControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export type animalControllerReadResponse200 = {
  data: AnimalResponse;
  status: 200;
};

export type animalControllerReadResponseSuccess = animalControllerReadResponse200 & {
  headers: Headers;
};
export const getAnimalControllerReadUrl = (id: number) => {
  return `http://localhost:4000/api/v1/animals/${id}`;
};

export const animalControllerRead = async (
  id: number,
  options?: RequestInit,
): Promise<animalControllerReadResponseSuccess> => {
  const res = await fetch(getAnimalControllerReadUrl(id), {
    credentials: 'include',
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: animalControllerReadResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as animalControllerReadResponseSuccess;
};

export const getAnimalControllerReadInfiniteQueryKey = (id?: number) => {
  return ['infinite', `http://localhost:4000/api/v1/animals/${id}`] as const;
};

export const getAnimalControllerReadQueryKey = (id?: number) => {
  return [`http://localhost:4000/api/v1/animals/${id}`] as const;
};

export const getAnimalControllerReadInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAnimalControllerReadInfiniteQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof animalControllerRead>>> = ({ signal }) =>
    animalControllerRead(id, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof animalControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AnimalControllerReadInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof animalControllerRead>>>;
export type AnimalControllerReadInfiniteQueryError = unknown;

export function useAnimalControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof animalControllerRead>>,
          TError,
          Awaited<ReturnType<typeof animalControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAnimalControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof animalControllerRead>>,
          TError,
          Awaited<ReturnType<typeof animalControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAnimalControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAnimalControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAnimalControllerReadInfiniteQueryOptions(id, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchAnimalControllerReadInfiniteQuery = async <
  TData = Awaited<ReturnType<typeof animalControllerRead>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getAnimalControllerReadInfiniteQueryOptions(id, options);

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
};

export const getAnimalControllerReadQueryOptions = <
  TData = Awaited<ReturnType<typeof animalControllerRead>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAnimalControllerReadQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof animalControllerRead>>> = ({ signal }) =>
    animalControllerRead(id, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof animalControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AnimalControllerReadQueryResult = NonNullable<Awaited<ReturnType<typeof animalControllerRead>>>;
export type AnimalControllerReadQueryError = unknown;

export function useAnimalControllerRead<TData = Awaited<ReturnType<typeof animalControllerRead>>, TError = unknown>(
  id: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof animalControllerRead>>,
          TError,
          Awaited<ReturnType<typeof animalControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAnimalControllerRead<TData = Awaited<ReturnType<typeof animalControllerRead>>, TError = unknown>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof animalControllerRead>>,
          TError,
          Awaited<ReturnType<typeof animalControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAnimalControllerRead<TData = Awaited<ReturnType<typeof animalControllerRead>>, TError = unknown>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAnimalControllerRead<TData = Awaited<ReturnType<typeof animalControllerRead>>, TError = unknown>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAnimalControllerReadQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchAnimalControllerReadQuery = async <
  TData = Awaited<ReturnType<typeof animalControllerRead>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getAnimalControllerReadQueryOptions(id, options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getAnimalControllerReadSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof animalControllerRead>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAnimalControllerReadQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof animalControllerRead>>> = ({ signal }) =>
    animalControllerRead(id, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof animalControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AnimalControllerReadSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof animalControllerRead>>>;
export type AnimalControllerReadSuspenseQueryError = unknown;

export function useAnimalControllerReadSuspense<
  TData = Awaited<ReturnType<typeof animalControllerRead>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAnimalControllerReadSuspense<
  TData = Awaited<ReturnType<typeof animalControllerRead>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAnimalControllerReadSuspense<
  TData = Awaited<ReturnType<typeof animalControllerRead>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAnimalControllerReadSuspense<
  TData = Awaited<ReturnType<typeof animalControllerRead>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAnimalControllerReadSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getAnimalControllerReadSuspenseInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAnimalControllerReadInfiniteQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof animalControllerRead>>> = ({ signal }) =>
    animalControllerRead(id, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseInfiniteQueryOptions<
    Awaited<ReturnType<typeof animalControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AnimalControllerReadSuspenseInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof animalControllerRead>>
>;
export type AnimalControllerReadSuspenseInfiniteQueryError = unknown;

export function useAnimalControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAnimalControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAnimalControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAnimalControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof animalControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof animalControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAnimalControllerReadSuspenseInfiniteQueryOptions(id, options);

  const query = useSuspenseInfiniteQuery(queryOptions, queryClient) as UseSuspenseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type animalControllerUpdateResponse200 = {
  data: AnimalResponse;
  status: 200;
};

export type animalControllerUpdateResponseSuccess = animalControllerUpdateResponse200 & {
  headers: Headers;
};
export const getAnimalControllerUpdateUrl = (id: number) => {
  return `http://localhost:4000/api/v1/animals/${id}`;
};

export const animalControllerUpdate = async (
  id: number,
  animalUpdateRequest: AnimalUpdateRequest,
  options?: RequestInit,
): Promise<animalControllerUpdateResponseSuccess> => {
  const res = await fetch(getAnimalControllerUpdateUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(animalUpdateRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: animalControllerUpdateResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as animalControllerUpdateResponseSuccess;
};

export const getAnimalControllerUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof animalControllerUpdate>>,
    TError,
    { id: number; data: AnimalUpdateRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof animalControllerUpdate>>,
  TError,
  { id: number; data: AnimalUpdateRequest },
  TContext
> => {
  const mutationKey = ['animalControllerUpdate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof animalControllerUpdate>>,
    { id: number; data: AnimalUpdateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return animalControllerUpdate(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AnimalControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof animalControllerUpdate>>>;
export type AnimalControllerUpdateMutationBody = AnimalUpdateRequest;
export type AnimalControllerUpdateMutationError = unknown;

export const useAnimalControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof animalControllerUpdate>>,
      TError,
      { id: number; data: AnimalUpdateRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof animalControllerUpdate>>,
  TError,
  { id: number; data: AnimalUpdateRequest },
  TContext
> => {
  const mutationOptions = getAnimalControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export type animalControllerDeleteResponse200 = {
  data: AnimalResponse;
  status: 200;
};

export type animalControllerDeleteResponseSuccess = animalControllerDeleteResponse200 & {
  headers: Headers;
};
export const getAnimalControllerDeleteUrl = (id: number) => {
  return `http://localhost:4000/api/v1/animals/${id}`;
};

export const animalControllerDelete = async (
  id: number,
  options?: RequestInit,
): Promise<animalControllerDeleteResponseSuccess> => {
  const res = await fetch(getAnimalControllerDeleteUrl(id), {
    credentials: 'include',
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: animalControllerDeleteResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as animalControllerDeleteResponseSuccess;
};

export const getAnimalControllerDeleteMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof animalControllerDelete>>, TError, { id: number }, TContext>;
  fetch?: RequestInit;
}): UseMutationOptions<Awaited<ReturnType<typeof animalControllerDelete>>, TError, { id: number }, TContext> => {
  const mutationKey = ['animalControllerDelete'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof animalControllerDelete>>, { id: number }> = (props) => {
    const { id } = props ?? {};

    return animalControllerDelete(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AnimalControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof animalControllerDelete>>>;

export type AnimalControllerDeleteMutationError = unknown;

export const useAnimalControllerDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof animalControllerDelete>>, TError, { id: number }, TContext>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof animalControllerDelete>>, TError, { id: number }, TContext> => {
  const mutationOptions = getAnimalControllerDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export type animalControllerUploadResponse201 = {
  data: FileResponse;
  status: 201;
};

export type animalControllerUploadResponseSuccess = animalControllerUploadResponse201 & {
  headers: Headers;
};
export const getAnimalControllerUploadUrl = () => {
  return `http://localhost:4000/api/v1/animals/thumbnail`;
};

export const animalControllerUpload = async (
  animalControllerUploadBody: AnimalControllerUploadBody,
  options?: RequestInit,
): Promise<animalControllerUploadResponseSuccess> => {
  const formData = new FormData();
  formData.append(`thumbnail`, animalControllerUploadBody.thumbnail);

  const res = await fetch(getAnimalControllerUploadUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    body: formData,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: animalControllerUploadResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as animalControllerUploadResponseSuccess;
};

export const getAnimalControllerUploadMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof animalControllerUpload>>,
    TError,
    { data: AnimalControllerUploadBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof animalControllerUpload>>,
  TError,
  { data: AnimalControllerUploadBody },
  TContext
> => {
  const mutationKey = ['animalControllerUpload'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof animalControllerUpload>>,
    { data: AnimalControllerUploadBody }
  > = (props) => {
    const { data } = props ?? {};

    return animalControllerUpload(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AnimalControllerUploadMutationResult = NonNullable<Awaited<ReturnType<typeof animalControllerUpload>>>;
export type AnimalControllerUploadMutationBody = AnimalControllerUploadBody;
export type AnimalControllerUploadMutationError = unknown;

export const useAnimalControllerUpload = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof animalControllerUpload>>,
      TError,
      { data: AnimalControllerUploadBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof animalControllerUpload>>,
  TError,
  { data: AnimalControllerUploadBody },
  TContext
> => {
  const mutationOptions = getAnimalControllerUploadMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
