/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useQuery, useSuspenseInfiniteQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import type { BreedControllerAll200, BreedControllerAllParams } from './index.schemas';

export type breedControllerAllResponse200 = {
  data: BreedControllerAll200;
  status: 200;
};

export type breedControllerAllResponseSuccess = breedControllerAllResponse200 & {
  headers: Headers;
};
export const getBreedControllerAllUrl = (params?: BreedControllerAllParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://localhost:4000/api/v1/breeds?${stringifiedParams}`
    : `http://localhost:4000/api/v1/breeds`;
};

export const breedControllerAll = async (
  params?: BreedControllerAllParams,
  options?: RequestInit,
): Promise<breedControllerAllResponseSuccess> => {
  const res = await fetch(getBreedControllerAllUrl(params), {
    credentials: 'include',
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: breedControllerAllResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as breedControllerAllResponseSuccess;
};

export const getBreedControllerAllInfiniteQueryKey = (params?: BreedControllerAllParams) => {
  return ['infinite', `http://localhost:4000/api/v1/breeds`, ...(params ? [params] : [])] as const;
};

export const getBreedControllerAllQueryKey = (params?: BreedControllerAllParams) => {
  return [`http://localhost:4000/api/v1/breeds`, ...(params ? [params] : [])] as const;
};

export const getBreedControllerAllInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['page']>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['page']
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBreedControllerAllInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof breedControllerAll>>,
    QueryKey,
    BreedControllerAllParams['page']
  > = ({ signal, pageParam }) =>
    breedControllerAll({ ...params, page: pageParam || params?.['page'] }, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof breedControllerAll>>,
    TError,
    TData,
    QueryKey,
    BreedControllerAllParams['page']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BreedControllerAllInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof breedControllerAll>>>;
export type BreedControllerAllInfiniteQueryError = unknown;

export function useBreedControllerAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['page']>,
  TError = unknown,
>(
  params: undefined | BreedControllerAllParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['page']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof breedControllerAll>>,
          TError,
          Awaited<ReturnType<typeof breedControllerAll>>,
          QueryKey
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['page']>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['page']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof breedControllerAll>>,
          TError,
          Awaited<ReturnType<typeof breedControllerAll>>,
          QueryKey
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['page']>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['page']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBreedControllerAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['page']>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['page']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBreedControllerAllInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchBreedControllerAllInfiniteQuery = async <
  TData = Awaited<ReturnType<typeof breedControllerAll>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['page']
      >
    >;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getBreedControllerAllInfiniteQueryOptions(params, options);

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
};

export const getBreedControllerAllQueryOptions = <
  TData = Awaited<ReturnType<typeof breedControllerAll>>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBreedControllerAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof breedControllerAll>>> = ({ signal }) =>
    breedControllerAll(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof breedControllerAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BreedControllerAllQueryResult = NonNullable<Awaited<ReturnType<typeof breedControllerAll>>>;
export type BreedControllerAllQueryError = unknown;

export function useBreedControllerAll<TData = Awaited<ReturnType<typeof breedControllerAll>>, TError = unknown>(
  params: undefined | BreedControllerAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof breedControllerAll>>,
          TError,
          Awaited<ReturnType<typeof breedControllerAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerAll<TData = Awaited<ReturnType<typeof breedControllerAll>>, TError = unknown>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof breedControllerAll>>,
          TError,
          Awaited<ReturnType<typeof breedControllerAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerAll<TData = Awaited<ReturnType<typeof breedControllerAll>>, TError = unknown>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBreedControllerAll<TData = Awaited<ReturnType<typeof breedControllerAll>>, TError = unknown>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBreedControllerAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchBreedControllerAllQuery = async <
  TData = Awaited<ReturnType<typeof breedControllerAll>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getBreedControllerAllQueryOptions(params, options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getBreedControllerAllSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof breedControllerAll>>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBreedControllerAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof breedControllerAll>>> = ({ signal }) =>
    breedControllerAll(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof breedControllerAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BreedControllerAllSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof breedControllerAll>>>;
export type BreedControllerAllSuspenseQueryError = unknown;

export function useBreedControllerAllSuspense<TData = Awaited<ReturnType<typeof breedControllerAll>>, TError = unknown>(
  params: undefined | BreedControllerAllParams,
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerAllSuspense<TData = Awaited<ReturnType<typeof breedControllerAll>>, TError = unknown>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerAllSuspense<TData = Awaited<ReturnType<typeof breedControllerAll>>, TError = unknown>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBreedControllerAllSuspense<TData = Awaited<ReturnType<typeof breedControllerAll>>, TError = unknown>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBreedControllerAllSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getBreedControllerAllSuspenseInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['page']>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['page']
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBreedControllerAllInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof breedControllerAll>>,
    QueryKey,
    BreedControllerAllParams['page']
  > = ({ signal, pageParam }) =>
    breedControllerAll({ ...params, page: pageParam || params?.['page'] }, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseInfiniteQueryOptions<
    Awaited<ReturnType<typeof breedControllerAll>>,
    TError,
    TData,
    QueryKey,
    BreedControllerAllParams['page']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BreedControllerAllSuspenseInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof breedControllerAll>>>;
export type BreedControllerAllSuspenseInfiniteQueryError = unknown;

export function useBreedControllerAllSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['page']>,
  TError = unknown,
>(
  params: undefined | BreedControllerAllParams,
  options: {
    query: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['page']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerAllSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['page']>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['page']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerAllSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['page']>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['page']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBreedControllerAllSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['page']>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['page']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBreedControllerAllSuspenseInfiniteQueryOptions(params, options);

  const query = useSuspenseInfiniteQuery(queryOptions, queryClient) as UseSuspenseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
