/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useQuery, useSuspenseInfiniteQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import type { BreedControllerRead200, BreedControllerReadParams } from './index.schemas';

export type breedControllerReadResponse200 = {
  data: BreedControllerRead200;
  status: 200;
};

export type breedControllerReadResponseSuccess = breedControllerReadResponse200 & {
  headers: Headers;
};
export const getBreedControllerReadUrl = (params?: BreedControllerReadParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://localhost:4000/api/v1/breeds?${stringifiedParams}`
    : `http://localhost:4000/api/v1/breeds`;
};

export const breedControllerRead = async (
  params?: BreedControllerReadParams,
  options?: RequestInit,
): Promise<breedControllerReadResponseSuccess> => {
  const res = await fetch(getBreedControllerReadUrl(params), {
    credentials: 'include',
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: breedControllerReadResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as breedControllerReadResponseSuccess;
};

export const getBreedControllerReadInfiniteQueryKey = (params?: BreedControllerReadParams) => {
  return ['infinite', `http://localhost:4000/api/v1/breeds`, ...(params ? [params] : [])] as const;
};

export const getBreedControllerReadQueryKey = (params?: BreedControllerReadParams) => {
  return [`http://localhost:4000/api/v1/breeds`, ...(params ? [params] : [])] as const;
};

export const getBreedControllerReadInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerRead>>>,
  TError = unknown,
>(
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBreedControllerReadInfiniteQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof breedControllerRead>>> = ({ signal }) =>
    breedControllerRead(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof breedControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BreedControllerReadInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof breedControllerRead>>>;
export type BreedControllerReadInfiniteQueryError = unknown;

export function useBreedControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerRead>>>,
  TError = unknown,
>(
  params: undefined | BreedControllerReadParams,
  options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof breedControllerRead>>,
          TError,
          Awaited<ReturnType<typeof breedControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerRead>>>,
  TError = unknown,
>(
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof breedControllerRead>>,
          TError,
          Awaited<ReturnType<typeof breedControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerRead>>>,
  TError = unknown,
>(
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBreedControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerRead>>>,
  TError = unknown,
>(
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBreedControllerReadInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchBreedControllerReadInfiniteQuery = async <
  TData = Awaited<ReturnType<typeof breedControllerRead>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getBreedControllerReadInfiniteQueryOptions(params, options);

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
};

export const getBreedControllerReadQueryOptions = <
  TData = Awaited<ReturnType<typeof breedControllerRead>>,
  TError = unknown,
>(
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBreedControllerReadQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof breedControllerRead>>> = ({ signal }) =>
    breedControllerRead(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof breedControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BreedControllerReadQueryResult = NonNullable<Awaited<ReturnType<typeof breedControllerRead>>>;
export type BreedControllerReadQueryError = unknown;

export function useBreedControllerRead<TData = Awaited<ReturnType<typeof breedControllerRead>>, TError = unknown>(
  params: undefined | BreedControllerReadParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof breedControllerRead>>,
          TError,
          Awaited<ReturnType<typeof breedControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerRead<TData = Awaited<ReturnType<typeof breedControllerRead>>, TError = unknown>(
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof breedControllerRead>>,
          TError,
          Awaited<ReturnType<typeof breedControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerRead<TData = Awaited<ReturnType<typeof breedControllerRead>>, TError = unknown>(
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBreedControllerRead<TData = Awaited<ReturnType<typeof breedControllerRead>>, TError = unknown>(
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBreedControllerReadQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchBreedControllerReadQuery = async <
  TData = Awaited<ReturnType<typeof breedControllerRead>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getBreedControllerReadQueryOptions(params, options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getBreedControllerReadSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof breedControllerRead>>,
  TError = unknown,
>(
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBreedControllerReadQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof breedControllerRead>>> = ({ signal }) =>
    breedControllerRead(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof breedControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BreedControllerReadSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof breedControllerRead>>>;
export type BreedControllerReadSuspenseQueryError = unknown;

export function useBreedControllerReadSuspense<
  TData = Awaited<ReturnType<typeof breedControllerRead>>,
  TError = unknown,
>(
  params: undefined | BreedControllerReadParams,
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerReadSuspense<
  TData = Awaited<ReturnType<typeof breedControllerRead>>,
  TError = unknown,
>(
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerReadSuspense<
  TData = Awaited<ReturnType<typeof breedControllerRead>>,
  TError = unknown,
>(
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBreedControllerReadSuspense<
  TData = Awaited<ReturnType<typeof breedControllerRead>>,
  TError = unknown,
>(
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBreedControllerReadSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getBreedControllerReadSuspenseInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerRead>>>,
  TError = unknown,
>(
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBreedControllerReadInfiniteQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof breedControllerRead>>> = ({ signal }) =>
    breedControllerRead(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseInfiniteQueryOptions<
    Awaited<ReturnType<typeof breedControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BreedControllerReadSuspenseInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof breedControllerRead>>
>;
export type BreedControllerReadSuspenseInfiniteQueryError = unknown;

export function useBreedControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerRead>>>,
  TError = unknown,
>(
  params: undefined | BreedControllerReadParams,
  options: {
    query: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerRead>>>,
  TError = unknown,
>(
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerRead>>>,
  TError = unknown,
>(
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBreedControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerRead>>>,
  TError = unknown,
>(
  params?: BreedControllerReadParams,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof breedControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBreedControllerReadSuspenseInfiniteQueryOptions(params, options);

  const query = useSuspenseInfiniteQuery(queryOptions, queryClient) as UseSuspenseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
