/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useQuery, useSuspenseInfiniteQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import type { BreedControllerAll200, BreedControllerAllParams } from './index.schemas';

import { customFetch } from './mutator/custom-fetch';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type breedControllerAllResponse200 = {
  data: BreedControllerAll200;
  status: 200;
};

export type breedControllerAllResponseSuccess = breedControllerAllResponse200 & {
  headers: Headers;
};
export type breedControllerAllResponse = breedControllerAllResponseSuccess;

export const getBreedControllerAllUrl = (params?: BreedControllerAllParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/breeds?${stringifiedParams}` : `/api/v1/breeds`;
};

export const breedControllerAll = async (
  params?: BreedControllerAllParams,
  options?: RequestInit,
): Promise<breedControllerAllResponse> => {
  return customFetch<breedControllerAllResponse>(getBreedControllerAllUrl(params), {
    credentials: 'include',
    ...options,
    method: 'GET',
  });
};

export const getBreedControllerAllInfiniteQueryKey = (params?: BreedControllerAllParams) => {
  return ['infinite', `/api/v1/breeds`, ...(params ? [params] : [])] as const;
};

export const getBreedControllerAllQueryKey = (params?: BreedControllerAllParams) => {
  return [`/api/v1/breeds`, ...(params ? [params] : [])] as const;
};

export const getBreedControllerAllInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['cursor']
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBreedControllerAllInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof breedControllerAll>>,
    QueryKey,
    BreedControllerAllParams['cursor']
  > = ({ signal, pageParam }) =>
    breedControllerAll({ ...params, cursor: pageParam || params?.['cursor'] }, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof breedControllerAll>>,
    TError,
    TData,
    QueryKey,
    BreedControllerAllParams['cursor']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BreedControllerAllInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof breedControllerAll>>>;
export type BreedControllerAllInfiniteQueryError = unknown;

export function useBreedControllerAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['cursor']>,
  TError = unknown,
>(
  params: undefined | BreedControllerAllParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['cursor']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof breedControllerAll>>,
          TError,
          Awaited<ReturnType<typeof breedControllerAll>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['cursor']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof breedControllerAll>>,
          TError,
          Awaited<ReturnType<typeof breedControllerAll>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['cursor']
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBreedControllerAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['cursor']
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBreedControllerAllInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchBreedControllerAllInfiniteQuery = async <
  TData = Awaited<ReturnType<typeof breedControllerAll>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['cursor']
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): Promise<QueryClient> => {
  const queryOptions = getBreedControllerAllInfiniteQueryOptions(params, options);

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
};

export const getBreedControllerAllQueryOptions = <
  TData = Awaited<ReturnType<typeof breedControllerAll>>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBreedControllerAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof breedControllerAll>>> = ({ signal }) =>
    breedControllerAll(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof breedControllerAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BreedControllerAllQueryResult = NonNullable<Awaited<ReturnType<typeof breedControllerAll>>>;
export type BreedControllerAllQueryError = unknown;

export function useBreedControllerAll<TData = Awaited<ReturnType<typeof breedControllerAll>>, TError = unknown>(
  params: undefined | BreedControllerAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof breedControllerAll>>,
          TError,
          Awaited<ReturnType<typeof breedControllerAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerAll<TData = Awaited<ReturnType<typeof breedControllerAll>>, TError = unknown>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof breedControllerAll>>,
          TError,
          Awaited<ReturnType<typeof breedControllerAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerAll<TData = Awaited<ReturnType<typeof breedControllerAll>>, TError = unknown>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBreedControllerAll<TData = Awaited<ReturnType<typeof breedControllerAll>>, TError = unknown>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBreedControllerAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchBreedControllerAllQuery = async <
  TData = Awaited<ReturnType<typeof breedControllerAll>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
): Promise<QueryClient> => {
  const queryOptions = getBreedControllerAllQueryOptions(params, options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getBreedControllerAllSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof breedControllerAll>>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBreedControllerAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof breedControllerAll>>> = ({ signal }) =>
    breedControllerAll(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof breedControllerAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BreedControllerAllSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof breedControllerAll>>>;
export type BreedControllerAllSuspenseQueryError = unknown;

export function useBreedControllerAllSuspense<TData = Awaited<ReturnType<typeof breedControllerAll>>, TError = unknown>(
  params: undefined | BreedControllerAllParams,
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerAllSuspense<TData = Awaited<ReturnType<typeof breedControllerAll>>, TError = unknown>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerAllSuspense<TData = Awaited<ReturnType<typeof breedControllerAll>>, TError = unknown>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBreedControllerAllSuspense<TData = Awaited<ReturnType<typeof breedControllerAll>>, TError = unknown>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof breedControllerAll>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBreedControllerAllSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getBreedControllerAllSuspenseInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['cursor']
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBreedControllerAllInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof breedControllerAll>>,
    QueryKey,
    BreedControllerAllParams['cursor']
  > = ({ signal, pageParam }) =>
    breedControllerAll({ ...params, cursor: pageParam || params?.['cursor'] }, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseInfiniteQueryOptions<
    Awaited<ReturnType<typeof breedControllerAll>>,
    TError,
    TData,
    QueryKey,
    BreedControllerAllParams['cursor']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BreedControllerAllSuspenseInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof breedControllerAll>>>;
export type BreedControllerAllSuspenseInfiniteQueryError = unknown;

export function useBreedControllerAllSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['cursor']>,
  TError = unknown,
>(
  params: undefined | BreedControllerAllParams,
  options: {
    query: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['cursor']
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerAllSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['cursor']
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBreedControllerAllSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['cursor']
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBreedControllerAllSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof breedControllerAll>>, BreedControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: BreedControllerAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof breedControllerAll>>,
        TError,
        TData,
        QueryKey,
        BreedControllerAllParams['cursor']
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBreedControllerAllSuspenseInfiniteQueryOptions(params, options);

  const query = useSuspenseInfiniteQuery(queryOptions, queryClient) as UseSuspenseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
