/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
export interface ProfileResponse {
  id: number;
  username: string;
  nickname: string;
  /** @nullable */
  profileImage: string | null;
}

/**
 * @nullable
 */
export type AuthInfoResponseProfile = ProfileResponse | null;

export interface AuthInfoResponse {
  /** @nullable */
  profile: AuthInfoResponseProfile;
}

export interface AuthRegisterRequest {
  nickname: string;
  username: string;
}

export interface AuthCheckDuplicateUsernameRequest {
  username: string;
}

export interface Pagination {
  page: number;
  total: number;
  limit: number;
  hasNextPage: boolean;
}

export type BreedResponseSpecies = (typeof BreedResponseSpecies)[keyof typeof BreedResponseSpecies];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BreedResponseSpecies = {
  DOG: 'DOG',
  CAT: 'CAT',
} as const;

export interface BreedResponse {
  id: number;
  name: string;
  species: BreedResponseSpecies;
}

export type AnimalResponseGender = (typeof AnimalResponseGender)[keyof typeof AnimalResponseGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnimalResponseGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;

export interface AnimalResponse {
  id: number;
  name: string;
  gender: AnimalResponseGender;
  birthday: string;
  /** @nullable */
  thumbnail: string | null;
  owner: ProfileResponse;
  breed: BreedResponse;
}

export type AnimalCreateRequestGender = (typeof AnimalCreateRequestGender)[keyof typeof AnimalCreateRequestGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnimalCreateRequestGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;

export interface AnimalCreateRequest {
  breedId: number;
  name: string;
  gender: AnimalCreateRequestGender;
  birthday: string;
  thumbnail?: string;
}

export type AnimalUpdateRequestGender = (typeof AnimalUpdateRequestGender)[keyof typeof AnimalUpdateRequestGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnimalUpdateRequestGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;

export interface AnimalUpdateRequest {
  breedId: number;
  name: string;
  gender: AnimalUpdateRequestGender;
  birthday: string;
  thumbnail?: string;
}

export interface FileResponse {
  path: string;
  size: number;
  width: number;
  height: number;
  mimetype: string;
}

export interface CursorPagination {
  /** @nullable */
  cursor: number | null;
  total: number;
  limit: number;
  hasNextPage: boolean;
}

export interface TagResponse {
  name: string;
  slug: string;
}

export interface PhotoResponse {
  id: number;
  image: FileResponse;
  /** @nullable */
  title: string | null;
  /** @nullable */
  description: string | null;
  likes: number;
  liked: boolean;
  tags: TagResponse[];
  author: ProfileResponse;
  animal: AnimalResponse;
}

export interface FileRequest {
  path: string;
  size: number;
  width: number;
  height: number;
  mimetype: string;
}

export interface PhotoCreateRequest {
  animalId: number;
  image: FileRequest;
  title?: string;
  description?: string;
  tags?: string[];
}

export interface PhotoUpdateRequest {
  animalId: number;
  image: FileRequest;
  title?: string;
  description?: string;
  tags?: string[];
}

export type AnimalControllerAll200AllOf = {
  items: AnimalResponse[];
};

export type AnimalControllerAll200 = Pagination & AnimalControllerAll200AllOf;

export type AnimalControllerUploadBody = {
  thumbnail: Blob;
};

export type ProfileControllerAnimals200AllOf = {
  items: AnimalResponse[];
};

export type ProfileControllerAnimals200 = Pagination & ProfileControllerAnimals200AllOf;

export type ProfileControllerPhotosParams = {
  cursor?: number;
  /**
   * @minimum 1
   */
  limit?: number;
};

export type ProfileControllerPhotos200AllOf = {
  items: PhotoResponse[];
};

export type ProfileControllerPhotos200 = CursorPagination & ProfileControllerPhotos200AllOf;

export type BreedControllerReadParams = {
  species?: BreedControllerReadSpecies;
};

export type BreedControllerReadSpecies = (typeof BreedControllerReadSpecies)[keyof typeof BreedControllerReadSpecies];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BreedControllerReadSpecies = {
  DOG: 'DOG',
  CAT: 'CAT',
} as const;

export type BreedControllerRead200AllOf = {
  items: BreedResponse[];
};

export type BreedControllerRead200 = Pagination & BreedControllerRead200AllOf;

export type PhotoControllerAllParams = {
  cursor?: number;
  /**
   * @minimum 1
   */
  limit?: number;
  sort?: PhotoControllerAllSort;
};

export type PhotoControllerAllSort = (typeof PhotoControllerAllSort)[keyof typeof PhotoControllerAllSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PhotoControllerAllSort = {
  POPULAR: 'POPULAR',
  LATEST: 'LATEST',
} as const;

export type PhotoControllerAll200AllOf = {
  items: PhotoResponse[];
};

export type PhotoControllerAll200 = CursorPagination & PhotoControllerAll200AllOf;

export type PhotoControllerUploadBody = {
  image: Blob;
};
