/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
export interface UserResponse {
  id: number;
  username: string;
  nickname: string;
  /** @nullable */
  profileImage: string | null;
}

/**
 * @nullable
 */
export type AuthInfoResponseProfile = UserResponse | null;

export interface AuthInfoResponse {
  /** @nullable */
  profile: AuthInfoResponseProfile;
}

export interface AuthRegisterRequest {
  nickname: string;
  username: string;
}

export interface AuthCheckDuplicateUsernameRequest {
  username: string;
}

export interface Pagination {
  page: number;
  total: number;
  limit: number;
  hasNextPage: boolean;
}

export type BreedResponseSpecies = (typeof BreedResponseSpecies)[keyof typeof BreedResponseSpecies];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BreedResponseSpecies = {
  DOG: 'DOG',
  CAT: 'CAT',
} as const;

export interface BreedResponse {
  id: number;
  name: string;
  species: BreedResponseSpecies;
}

export type AnimalResponseGender = (typeof AnimalResponseGender)[keyof typeof AnimalResponseGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnimalResponseGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;

export interface AnimalResponse {
  id: number;
  name: string;
  gender: AnimalResponseGender;
  birthday: string;
  /** @nullable */
  thumbnail: string | null;
  owner: UserResponse;
  breed: BreedResponse;
}

export type AnimalCreateRequestGender = (typeof AnimalCreateRequestGender)[keyof typeof AnimalCreateRequestGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnimalCreateRequestGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;

export interface AnimalCreateRequest {
  breedId: number;
  name: string;
  gender: AnimalCreateRequestGender;
  birthday: string;
  /** @nullable */
  thumbnail?: string | null;
}

export type AnimalUpdateRequestGender = (typeof AnimalUpdateRequestGender)[keyof typeof AnimalUpdateRequestGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnimalUpdateRequestGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;

export interface AnimalUpdateRequest {
  breedId: number;
  name: string;
  gender: AnimalUpdateRequestGender;
  birthday: string;
  /** @nullable */
  thumbnail?: string | null;
}

export interface FileResponse {
  path: string;
  size: number;
  width: number;
  height: number;
  mimetype: string;
}

export interface ProfileResponse {
  id: number;
  username: string;
  nickname: string;
  /** @nullable */
  profileImage: string | null;
  followers: number;
  followings: number;
  isFollowing: boolean;
  isOwner: boolean;
}

export interface CursorPagination {
  /** @nullable */
  cursor: number | null;
  total: number;
  limit: number;
  hasNextPage: boolean;
}

export interface TagResponse {
  name: string;
  slug: string;
}

export interface PhotoResponse {
  id: number;
  image: FileResponse;
  /** @nullable */
  title: string | null;
  /** @nullable */
  description: string | null;
  likes: number;
  liked: boolean;
  tags: TagResponse[];
  animals: AnimalResponse[];
  author: ProfileResponse;
}

export interface FileRequest {
  path: string;
  size: number;
  width: number;
  height: number;
  mimetype: string;
}

export interface PhotoCreateRequest {
  animalIds: number[];
  image: FileRequest;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  tags?: string[];
}

export interface PhotoUpdateRequest {
  animalIds: number[];
  image: FileRequest;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  tags?: string[];
}

export interface PhotoCommentCreateRequest {
  content: string;
  /** @nullable */
  parentId?: number | null;
  /** @nullable */
  mentionId?: number | null;
}

/**
 * @nullable
 */
export type PhotoCommentResponseMention = ProfileResponse | null;

export interface PhotoCommentResponse {
  id: number;
  content: string;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  parentId: number | null;
  /** @nullable */
  mention: PhotoCommentResponseMention;
  author: ProfileResponse;
}

export interface PhotoCommentUpdateRequest {
  content: string;
}

export type AnimalControllerAllParams = {
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   */
  limit?: number;
};

export type AnimalControllerAll200AllOf = {
  items: AnimalResponse[];
};

export type AnimalControllerAll200 = Pagination & AnimalControllerAll200AllOf;

export type AnimalControllerUploadBody = {
  thumbnail: Blob;
};

export type ProfileControllerAnimalsParams = {
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   */
  limit?: number;
};

export type ProfileControllerAnimals200AllOf = {
  items: AnimalResponse[];
};

export type ProfileControllerAnimals200 = Pagination & ProfileControllerAnimals200AllOf;

export type ProfileControllerPhotosParams = {
  cursor?: number;
  /**
   * @minimum 1
   */
  limit?: number;
};

export type ProfileControllerPhotos200AllOf = {
  items: PhotoResponse[];
};

export type ProfileControllerPhotos200 = CursorPagination & ProfileControllerPhotos200AllOf;

export type BreedControllerAllParams = {
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   */
  limit?: number;
  species?: BreedControllerAllSpecies;
};

export type BreedControllerAllSpecies = (typeof BreedControllerAllSpecies)[keyof typeof BreedControllerAllSpecies];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BreedControllerAllSpecies = {
  DOG: 'DOG',
  CAT: 'CAT',
} as const;

export type BreedControllerAll200AllOf = {
  items: BreedResponse[];
};

export type BreedControllerAll200 = Pagination & BreedControllerAll200AllOf;

export type PhotoControllerAllParams = {
  cursor?: number;
  /**
   * @minimum 1
   */
  limit?: number;
  sort?: PhotoControllerAllSort;
};

export type PhotoControllerAllSort = (typeof PhotoControllerAllSort)[keyof typeof PhotoControllerAllSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PhotoControllerAllSort = {
  POPULAR: 'POPULAR',
  LATEST: 'LATEST',
} as const;

export type PhotoControllerAll200AllOf = {
  items: PhotoResponse[];
};

export type PhotoControllerAll200 = CursorPagination & PhotoControllerAll200AllOf;

export type PhotoControllerUploadBody = {
  image: Blob;
};
