/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseInfiniteQuery,
  useSuspenseQuery,
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import type {
  FileResponse,
  PhotoControllerAll200,
  PhotoControllerAllParams,
  PhotoControllerUploadBody,
  PhotoCreateRequest,
  PhotoResponse,
  PhotoUpdateRequest,
} from './index.schemas';

export type photoControllerAllResponse200 = {
  data: PhotoControllerAll200;
  status: 200;
};

export type photoControllerAllResponseSuccess = photoControllerAllResponse200 & {
  headers: Headers;
};
export const getPhotoControllerAllUrl = (params?: PhotoControllerAllParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://localhost:4000/api/v1/photos?${stringifiedParams}`
    : `http://localhost:4000/api/v1/photos`;
};

export const photoControllerAll = async (
  params?: PhotoControllerAllParams,
  options?: RequestInit,
): Promise<photoControllerAllResponseSuccess> => {
  const res = await fetch(getPhotoControllerAllUrl(params), {
    credentials: 'include',
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: photoControllerAllResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as photoControllerAllResponseSuccess;
};

export const getPhotoControllerAllInfiniteQueryKey = (params?: PhotoControllerAllParams) => {
  return ['infinite', `http://localhost:4000/api/v1/photos`, ...(params ? [params] : [])] as const;
};

export const getPhotoControllerAllQueryKey = (params?: PhotoControllerAllParams) => {
  return [`http://localhost:4000/api/v1/photos`, ...(params ? [params] : [])] as const;
};

export const getPhotoControllerAllInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerAll>>, PhotoControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof photoControllerAll>>,
        TError,
        TData,
        QueryKey,
        PhotoControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPhotoControllerAllInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof photoControllerAll>>,
    QueryKey,
    PhotoControllerAllParams['cursor']
  > = ({ signal, pageParam }) =>
    photoControllerAll({ ...params, cursor: pageParam || params?.['cursor'] }, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof photoControllerAll>>,
    TError,
    TData,
    QueryKey,
    PhotoControllerAllParams['cursor']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PhotoControllerAllInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof photoControllerAll>>>;
export type PhotoControllerAllInfiniteQueryError = unknown;

export function usePhotoControllerAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerAll>>, PhotoControllerAllParams['cursor']>,
  TError = unknown,
>(
  params: undefined | PhotoControllerAllParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof photoControllerAll>>,
        TError,
        TData,
        QueryKey,
        PhotoControllerAllParams['cursor']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof photoControllerAll>>,
          TError,
          Awaited<ReturnType<typeof photoControllerAll>>,
          QueryKey
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerAll>>, PhotoControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof photoControllerAll>>,
        TError,
        TData,
        QueryKey,
        PhotoControllerAllParams['cursor']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof photoControllerAll>>,
          TError,
          Awaited<ReturnType<typeof photoControllerAll>>,
          QueryKey
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerAll>>, PhotoControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof photoControllerAll>>,
        TError,
        TData,
        QueryKey,
        PhotoControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePhotoControllerAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerAll>>, PhotoControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof photoControllerAll>>,
        TError,
        TData,
        QueryKey,
        PhotoControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPhotoControllerAllInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchPhotoControllerAllInfiniteQuery = async <
  TData = Awaited<ReturnType<typeof photoControllerAll>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof photoControllerAll>>,
        TError,
        TData,
        QueryKey,
        PhotoControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getPhotoControllerAllInfiniteQueryOptions(params, options);

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
};

export const getPhotoControllerAllQueryOptions = <
  TData = Awaited<ReturnType<typeof photoControllerAll>>,
  TError = unknown,
>(
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPhotoControllerAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof photoControllerAll>>> = ({ signal }) =>
    photoControllerAll(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof photoControllerAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PhotoControllerAllQueryResult = NonNullable<Awaited<ReturnType<typeof photoControllerAll>>>;
export type PhotoControllerAllQueryError = unknown;

export function usePhotoControllerAll<TData = Awaited<ReturnType<typeof photoControllerAll>>, TError = unknown>(
  params: undefined | PhotoControllerAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof photoControllerAll>>,
          TError,
          Awaited<ReturnType<typeof photoControllerAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerAll<TData = Awaited<ReturnType<typeof photoControllerAll>>, TError = unknown>(
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof photoControllerAll>>,
          TError,
          Awaited<ReturnType<typeof photoControllerAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerAll<TData = Awaited<ReturnType<typeof photoControllerAll>>, TError = unknown>(
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePhotoControllerAll<TData = Awaited<ReturnType<typeof photoControllerAll>>, TError = unknown>(
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPhotoControllerAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchPhotoControllerAllQuery = async <
  TData = Awaited<ReturnType<typeof photoControllerAll>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getPhotoControllerAllQueryOptions(params, options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getPhotoControllerAllSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof photoControllerAll>>,
  TError = unknown,
>(
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof photoControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPhotoControllerAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof photoControllerAll>>> = ({ signal }) =>
    photoControllerAll(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof photoControllerAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PhotoControllerAllSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof photoControllerAll>>>;
export type PhotoControllerAllSuspenseQueryError = unknown;

export function usePhotoControllerAllSuspense<TData = Awaited<ReturnType<typeof photoControllerAll>>, TError = unknown>(
  params: undefined | PhotoControllerAllParams,
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof photoControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerAllSuspense<TData = Awaited<ReturnType<typeof photoControllerAll>>, TError = unknown>(
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof photoControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerAllSuspense<TData = Awaited<ReturnType<typeof photoControllerAll>>, TError = unknown>(
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof photoControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePhotoControllerAllSuspense<TData = Awaited<ReturnType<typeof photoControllerAll>>, TError = unknown>(
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof photoControllerAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPhotoControllerAllSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getPhotoControllerAllSuspenseInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerAll>>, PhotoControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof photoControllerAll>>,
        TError,
        TData,
        QueryKey,
        PhotoControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPhotoControllerAllInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof photoControllerAll>>,
    QueryKey,
    PhotoControllerAllParams['cursor']
  > = ({ signal, pageParam }) =>
    photoControllerAll({ ...params, cursor: pageParam || params?.['cursor'] }, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseInfiniteQueryOptions<
    Awaited<ReturnType<typeof photoControllerAll>>,
    TError,
    TData,
    QueryKey,
    PhotoControllerAllParams['cursor']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PhotoControllerAllSuspenseInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof photoControllerAll>>>;
export type PhotoControllerAllSuspenseInfiniteQueryError = unknown;

export function usePhotoControllerAllSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerAll>>, PhotoControllerAllParams['cursor']>,
  TError = unknown,
>(
  params: undefined | PhotoControllerAllParams,
  options: {
    query: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof photoControllerAll>>,
        TError,
        TData,
        QueryKey,
        PhotoControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerAllSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerAll>>, PhotoControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof photoControllerAll>>,
        TError,
        TData,
        QueryKey,
        PhotoControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerAllSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerAll>>, PhotoControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof photoControllerAll>>,
        TError,
        TData,
        QueryKey,
        PhotoControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePhotoControllerAllSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerAll>>, PhotoControllerAllParams['cursor']>,
  TError = unknown,
>(
  params?: PhotoControllerAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof photoControllerAll>>,
        TError,
        TData,
        QueryKey,
        PhotoControllerAllParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPhotoControllerAllSuspenseInfiniteQueryOptions(params, options);

  const query = useSuspenseInfiniteQuery(queryOptions, queryClient) as UseSuspenseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type photoControllerCreateResponse201 = {
  data: PhotoResponse;
  status: 201;
};

export type photoControllerCreateResponseSuccess = photoControllerCreateResponse201 & {
  headers: Headers;
};
export const getPhotoControllerCreateUrl = () => {
  return `http://localhost:4000/api/v1/photos`;
};

export const photoControllerCreate = async (
  photoCreateRequest: PhotoCreateRequest,
  options?: RequestInit,
): Promise<photoControllerCreateResponseSuccess> => {
  const res = await fetch(getPhotoControllerCreateUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(photoCreateRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: photoControllerCreateResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as photoControllerCreateResponseSuccess;
};

export const getPhotoControllerCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof photoControllerCreate>>,
    TError,
    { data: PhotoCreateRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof photoControllerCreate>>,
  TError,
  { data: PhotoCreateRequest },
  TContext
> => {
  const mutationKey = ['photoControllerCreate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof photoControllerCreate>>,
    { data: PhotoCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return photoControllerCreate(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PhotoControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof photoControllerCreate>>>;
export type PhotoControllerCreateMutationBody = PhotoCreateRequest;
export type PhotoControllerCreateMutationError = unknown;

export const usePhotoControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof photoControllerCreate>>,
      TError,
      { data: PhotoCreateRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof photoControllerCreate>>,
  TError,
  { data: PhotoCreateRequest },
  TContext
> => {
  const mutationOptions = getPhotoControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export type photoControllerReadResponse200 = {
  data: PhotoResponse;
  status: 200;
};

export type photoControllerReadResponseSuccess = photoControllerReadResponse200 & {
  headers: Headers;
};
export const getPhotoControllerReadUrl = (id: number) => {
  return `http://localhost:4000/api/v1/photos/${id}`;
};

export const photoControllerRead = async (
  id: number,
  options?: RequestInit,
): Promise<photoControllerReadResponseSuccess> => {
  const res = await fetch(getPhotoControllerReadUrl(id), {
    credentials: 'include',
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: photoControllerReadResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as photoControllerReadResponseSuccess;
};

export const getPhotoControllerReadInfiniteQueryKey = (id?: number) => {
  return ['infinite', `http://localhost:4000/api/v1/photos/${id}`] as const;
};

export const getPhotoControllerReadQueryKey = (id?: number) => {
  return [`http://localhost:4000/api/v1/photos/${id}`] as const;
};

export const getPhotoControllerReadInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPhotoControllerReadInfiniteQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof photoControllerRead>>> = ({ signal }) =>
    photoControllerRead(id, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof photoControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PhotoControllerReadInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof photoControllerRead>>>;
export type PhotoControllerReadInfiniteQueryError = unknown;

export function usePhotoControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof photoControllerRead>>,
          TError,
          Awaited<ReturnType<typeof photoControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof photoControllerRead>>,
          TError,
          Awaited<ReturnType<typeof photoControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePhotoControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPhotoControllerReadInfiniteQueryOptions(id, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchPhotoControllerReadInfiniteQuery = async <
  TData = Awaited<ReturnType<typeof photoControllerRead>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getPhotoControllerReadInfiniteQueryOptions(id, options);

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
};

export const getPhotoControllerReadQueryOptions = <
  TData = Awaited<ReturnType<typeof photoControllerRead>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPhotoControllerReadQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof photoControllerRead>>> = ({ signal }) =>
    photoControllerRead(id, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof photoControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PhotoControllerReadQueryResult = NonNullable<Awaited<ReturnType<typeof photoControllerRead>>>;
export type PhotoControllerReadQueryError = unknown;

export function usePhotoControllerRead<TData = Awaited<ReturnType<typeof photoControllerRead>>, TError = unknown>(
  id: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof photoControllerRead>>,
          TError,
          Awaited<ReturnType<typeof photoControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerRead<TData = Awaited<ReturnType<typeof photoControllerRead>>, TError = unknown>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof photoControllerRead>>,
          TError,
          Awaited<ReturnType<typeof photoControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerRead<TData = Awaited<ReturnType<typeof photoControllerRead>>, TError = unknown>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePhotoControllerRead<TData = Awaited<ReturnType<typeof photoControllerRead>>, TError = unknown>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPhotoControllerReadQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchPhotoControllerReadQuery = async <
  TData = Awaited<ReturnType<typeof photoControllerRead>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getPhotoControllerReadQueryOptions(id, options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getPhotoControllerReadSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof photoControllerRead>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPhotoControllerReadQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof photoControllerRead>>> = ({ signal }) =>
    photoControllerRead(id, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof photoControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PhotoControllerReadSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof photoControllerRead>>>;
export type PhotoControllerReadSuspenseQueryError = unknown;

export function usePhotoControllerReadSuspense<
  TData = Awaited<ReturnType<typeof photoControllerRead>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerReadSuspense<
  TData = Awaited<ReturnType<typeof photoControllerRead>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerReadSuspense<
  TData = Awaited<ReturnType<typeof photoControllerRead>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePhotoControllerReadSuspense<
  TData = Awaited<ReturnType<typeof photoControllerRead>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPhotoControllerReadSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getPhotoControllerReadSuspenseInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPhotoControllerReadInfiniteQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof photoControllerRead>>> = ({ signal }) =>
    photoControllerRead(id, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseInfiniteQueryOptions<
    Awaited<ReturnType<typeof photoControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PhotoControllerReadSuspenseInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof photoControllerRead>>
>;
export type PhotoControllerReadSuspenseInfiniteQueryError = unknown;

export function usePhotoControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePhotoControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPhotoControllerReadSuspenseInfiniteQueryOptions(id, options);

  const query = useSuspenseInfiniteQuery(queryOptions, queryClient) as UseSuspenseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type photoControllerUpdateResponse200 = {
  data: PhotoResponse;
  status: 200;
};

export type photoControllerUpdateResponseSuccess = photoControllerUpdateResponse200 & {
  headers: Headers;
};
export const getPhotoControllerUpdateUrl = (id: number) => {
  return `http://localhost:4000/api/v1/photos/${id}`;
};

export const photoControllerUpdate = async (
  id: number,
  photoUpdateRequest: PhotoUpdateRequest,
  options?: RequestInit,
): Promise<photoControllerUpdateResponseSuccess> => {
  const res = await fetch(getPhotoControllerUpdateUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(photoUpdateRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: photoControllerUpdateResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as photoControllerUpdateResponseSuccess;
};

export const getPhotoControllerUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof photoControllerUpdate>>,
    TError,
    { id: number; data: PhotoUpdateRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof photoControllerUpdate>>,
  TError,
  { id: number; data: PhotoUpdateRequest },
  TContext
> => {
  const mutationKey = ['photoControllerUpdate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof photoControllerUpdate>>,
    { id: number; data: PhotoUpdateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return photoControllerUpdate(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PhotoControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof photoControllerUpdate>>>;
export type PhotoControllerUpdateMutationBody = PhotoUpdateRequest;
export type PhotoControllerUpdateMutationError = unknown;

export const usePhotoControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof photoControllerUpdate>>,
      TError,
      { id: number; data: PhotoUpdateRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof photoControllerUpdate>>,
  TError,
  { id: number; data: PhotoUpdateRequest },
  TContext
> => {
  const mutationOptions = getPhotoControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export type photoControllerDeleteResponse200 = {
  data: PhotoResponse;
  status: 200;
};

export type photoControllerDeleteResponseSuccess = photoControllerDeleteResponse200 & {
  headers: Headers;
};
export const getPhotoControllerDeleteUrl = (id: number) => {
  return `http://localhost:4000/api/v1/photos/${id}`;
};

export const photoControllerDelete = async (
  id: number,
  options?: RequestInit,
): Promise<photoControllerDeleteResponseSuccess> => {
  const res = await fetch(getPhotoControllerDeleteUrl(id), {
    credentials: 'include',
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: photoControllerDeleteResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as photoControllerDeleteResponseSuccess;
};

export const getPhotoControllerDeleteMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof photoControllerDelete>>, TError, { id: number }, TContext>;
  fetch?: RequestInit;
}): UseMutationOptions<Awaited<ReturnType<typeof photoControllerDelete>>, TError, { id: number }, TContext> => {
  const mutationKey = ['photoControllerDelete'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof photoControllerDelete>>, { id: number }> = (props) => {
    const { id } = props ?? {};

    return photoControllerDelete(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PhotoControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof photoControllerDelete>>>;

export type PhotoControllerDeleteMutationError = unknown;

export const usePhotoControllerDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof photoControllerDelete>>, TError, { id: number }, TContext>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof photoControllerDelete>>, TError, { id: number }, TContext> => {
  const mutationOptions = getPhotoControllerDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export type photoControllerLikeResponse200 = {
  data: void;
  status: 200;
};

export type photoControllerLikeResponseSuccess = photoControllerLikeResponse200 & {
  headers: Headers;
};
export const getPhotoControllerLikeUrl = (id: number) => {
  return `http://localhost:4000/api/v1/photos/${id}/likes`;
};

export const photoControllerLike = async (
  id: number,
  options?: RequestInit,
): Promise<photoControllerLikeResponseSuccess> => {
  const res = await fetch(getPhotoControllerLikeUrl(id), {
    credentials: 'include',
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: photoControllerLikeResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as photoControllerLikeResponseSuccess;
};

export const getPhotoControllerLikeMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof photoControllerLike>>, TError, { id: number }, TContext>;
  fetch?: RequestInit;
}): UseMutationOptions<Awaited<ReturnType<typeof photoControllerLike>>, TError, { id: number }, TContext> => {
  const mutationKey = ['photoControllerLike'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof photoControllerLike>>, { id: number }> = (props) => {
    const { id } = props ?? {};

    return photoControllerLike(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PhotoControllerLikeMutationResult = NonNullable<Awaited<ReturnType<typeof photoControllerLike>>>;

export type PhotoControllerLikeMutationError = unknown;

export const usePhotoControllerLike = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof photoControllerLike>>, TError, { id: number }, TContext>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof photoControllerLike>>, TError, { id: number }, TContext> => {
  const mutationOptions = getPhotoControllerLikeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export type photoControllerUnlikeResponse200 = {
  data: void;
  status: 200;
};

export type photoControllerUnlikeResponseSuccess = photoControllerUnlikeResponse200 & {
  headers: Headers;
};
export const getPhotoControllerUnlikeUrl = (id: number) => {
  return `http://localhost:4000/api/v1/photos/${id}/likes`;
};

export const photoControllerUnlike = async (
  id: number,
  options?: RequestInit,
): Promise<photoControllerUnlikeResponseSuccess> => {
  const res = await fetch(getPhotoControllerUnlikeUrl(id), {
    credentials: 'include',
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: photoControllerUnlikeResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as photoControllerUnlikeResponseSuccess;
};

export const getPhotoControllerUnlikeMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof photoControllerUnlike>>, TError, { id: number }, TContext>;
  fetch?: RequestInit;
}): UseMutationOptions<Awaited<ReturnType<typeof photoControllerUnlike>>, TError, { id: number }, TContext> => {
  const mutationKey = ['photoControllerUnlike'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof photoControllerUnlike>>, { id: number }> = (props) => {
    const { id } = props ?? {};

    return photoControllerUnlike(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PhotoControllerUnlikeMutationResult = NonNullable<Awaited<ReturnType<typeof photoControllerUnlike>>>;

export type PhotoControllerUnlikeMutationError = unknown;

export const usePhotoControllerUnlike = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof photoControllerUnlike>>, TError, { id: number }, TContext>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof photoControllerUnlike>>, TError, { id: number }, TContext> => {
  const mutationOptions = getPhotoControllerUnlikeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export type photoControllerUploadResponse201 = {
  data: FileResponse;
  status: 201;
};

export type photoControllerUploadResponseSuccess = photoControllerUploadResponse201 & {
  headers: Headers;
};
export const getPhotoControllerUploadUrl = () => {
  return `http://localhost:4000/api/v1/photos/image`;
};

export const photoControllerUpload = async (
  photoControllerUploadBody: PhotoControllerUploadBody,
  options?: RequestInit,
): Promise<photoControllerUploadResponseSuccess> => {
  const formData = new FormData();
  formData.append(`image`, photoControllerUploadBody.image);

  const res = await fetch(getPhotoControllerUploadUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    body: formData,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: photoControllerUploadResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as photoControllerUploadResponseSuccess;
};

export const getPhotoControllerUploadMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof photoControllerUpload>>,
    TError,
    { data: PhotoControllerUploadBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof photoControllerUpload>>,
  TError,
  { data: PhotoControllerUploadBody },
  TContext
> => {
  const mutationKey = ['photoControllerUpload'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof photoControllerUpload>>,
    { data: PhotoControllerUploadBody }
  > = (props) => {
    const { data } = props ?? {};

    return photoControllerUpload(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PhotoControllerUploadMutationResult = NonNullable<Awaited<ReturnType<typeof photoControllerUpload>>>;
export type PhotoControllerUploadMutationBody = PhotoControllerUploadBody;
export type PhotoControllerUploadMutationError = unknown;

export const usePhotoControllerUpload = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof photoControllerUpload>>,
      TError,
      { data: PhotoControllerUploadBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof photoControllerUpload>>,
  TError,
  { data: PhotoControllerUploadBody },
  TContext
> => {
  const mutationOptions = getPhotoControllerUploadMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
