/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseInfiniteQuery,
  useSuspenseQuery,
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import type {
  FileResponse,
  PhotoControllerUploadBody,
  PhotoCreateRequest,
  PhotoResponse,
  PhotoUpdateRequest,
} from './index.schemas';

export type photoControllerReadResponse200 = {
  data: PhotoResponse;
  status: 200;
};

export type photoControllerReadResponseSuccess = photoControllerReadResponse200 & {
  headers: Headers;
};
export const getPhotoControllerReadUrl = (id: number) => {
  return `http://localhost:4000/api/v1/photos/${id}`;
};

export const photoControllerRead = async (
  id: number,
  options?: RequestInit,
): Promise<photoControllerReadResponseSuccess> => {
  const res = await fetch(getPhotoControllerReadUrl(id), {
    credentials: 'include',
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: photoControllerReadResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as photoControllerReadResponseSuccess;
};

export const getPhotoControllerReadInfiniteQueryKey = (id?: number) => {
  return ['infinite', `http://localhost:4000/api/v1/photos/${id}`] as const;
};

export const getPhotoControllerReadQueryKey = (id?: number) => {
  return [`http://localhost:4000/api/v1/photos/${id}`] as const;
};

export const getPhotoControllerReadInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPhotoControllerReadInfiniteQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof photoControllerRead>>> = ({ signal }) =>
    photoControllerRead(id, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof photoControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PhotoControllerReadInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof photoControllerRead>>>;
export type PhotoControllerReadInfiniteQueryError = unknown;

export function usePhotoControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof photoControllerRead>>,
          TError,
          Awaited<ReturnType<typeof photoControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof photoControllerRead>>,
          TError,
          Awaited<ReturnType<typeof photoControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePhotoControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPhotoControllerReadInfiniteQueryOptions(id, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchPhotoControllerReadInfiniteQuery = async <
  TData = Awaited<ReturnType<typeof photoControllerRead>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getPhotoControllerReadInfiniteQueryOptions(id, options);

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
};

export const getPhotoControllerReadQueryOptions = <
  TData = Awaited<ReturnType<typeof photoControllerRead>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPhotoControllerReadQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof photoControllerRead>>> = ({ signal }) =>
    photoControllerRead(id, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof photoControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PhotoControllerReadQueryResult = NonNullable<Awaited<ReturnType<typeof photoControllerRead>>>;
export type PhotoControllerReadQueryError = unknown;

export function usePhotoControllerRead<TData = Awaited<ReturnType<typeof photoControllerRead>>, TError = unknown>(
  id: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof photoControllerRead>>,
          TError,
          Awaited<ReturnType<typeof photoControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerRead<TData = Awaited<ReturnType<typeof photoControllerRead>>, TError = unknown>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof photoControllerRead>>,
          TError,
          Awaited<ReturnType<typeof photoControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerRead<TData = Awaited<ReturnType<typeof photoControllerRead>>, TError = unknown>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePhotoControllerRead<TData = Awaited<ReturnType<typeof photoControllerRead>>, TError = unknown>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPhotoControllerReadQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchPhotoControllerReadQuery = async <
  TData = Awaited<ReturnType<typeof photoControllerRead>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getPhotoControllerReadQueryOptions(id, options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getPhotoControllerReadSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof photoControllerRead>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPhotoControllerReadQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof photoControllerRead>>> = ({ signal }) =>
    photoControllerRead(id, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof photoControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PhotoControllerReadSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof photoControllerRead>>>;
export type PhotoControllerReadSuspenseQueryError = unknown;

export function usePhotoControllerReadSuspense<
  TData = Awaited<ReturnType<typeof photoControllerRead>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerReadSuspense<
  TData = Awaited<ReturnType<typeof photoControllerRead>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerReadSuspense<
  TData = Awaited<ReturnType<typeof photoControllerRead>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePhotoControllerReadSuspense<
  TData = Awaited<ReturnType<typeof photoControllerRead>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPhotoControllerReadSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getPhotoControllerReadSuspenseInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPhotoControllerReadInfiniteQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof photoControllerRead>>> = ({ signal }) =>
    photoControllerRead(id, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseInfiniteQueryOptions<
    Awaited<ReturnType<typeof photoControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PhotoControllerReadSuspenseInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof photoControllerRead>>
>;
export type PhotoControllerReadSuspenseInfiniteQueryError = unknown;

export function usePhotoControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePhotoControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePhotoControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof photoControllerRead>>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof photoControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPhotoControllerReadSuspenseInfiniteQueryOptions(id, options);

  const query = useSuspenseInfiniteQuery(queryOptions, queryClient) as UseSuspenseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type photoControllerUpdateResponse200 = {
  data: PhotoResponse;
  status: 200;
};

export type photoControllerUpdateResponseSuccess = photoControllerUpdateResponse200 & {
  headers: Headers;
};
export const getPhotoControllerUpdateUrl = (id: number) => {
  return `http://localhost:4000/api/v1/photos/${id}`;
};

export const photoControllerUpdate = async (
  id: number,
  photoUpdateRequest: PhotoUpdateRequest,
  options?: RequestInit,
): Promise<photoControllerUpdateResponseSuccess> => {
  const res = await fetch(getPhotoControllerUpdateUrl(id), {
    credentials: 'include',
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(photoUpdateRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: photoControllerUpdateResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as photoControllerUpdateResponseSuccess;
};

export const getPhotoControllerUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof photoControllerUpdate>>,
    TError,
    { id: number; data: PhotoUpdateRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof photoControllerUpdate>>,
  TError,
  { id: number; data: PhotoUpdateRequest },
  TContext
> => {
  const mutationKey = ['photoControllerUpdate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof photoControllerUpdate>>,
    { id: number; data: PhotoUpdateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return photoControllerUpdate(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PhotoControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof photoControllerUpdate>>>;
export type PhotoControllerUpdateMutationBody = PhotoUpdateRequest;
export type PhotoControllerUpdateMutationError = unknown;

export const usePhotoControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof photoControllerUpdate>>,
      TError,
      { id: number; data: PhotoUpdateRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof photoControllerUpdate>>,
  TError,
  { id: number; data: PhotoUpdateRequest },
  TContext
> => {
  const mutationOptions = getPhotoControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export type photoControllerCreateResponse201 = {
  data: PhotoResponse;
  status: 201;
};

export type photoControllerCreateResponseSuccess = photoControllerCreateResponse201 & {
  headers: Headers;
};
export const getPhotoControllerCreateUrl = () => {
  return `http://localhost:4000/api/v1/photos`;
};

export const photoControllerCreate = async (
  photoCreateRequest: PhotoCreateRequest,
  options?: RequestInit,
): Promise<photoControllerCreateResponseSuccess> => {
  const res = await fetch(getPhotoControllerCreateUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(photoCreateRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: photoControllerCreateResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as photoControllerCreateResponseSuccess;
};

export const getPhotoControllerCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof photoControllerCreate>>,
    TError,
    { data: PhotoCreateRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof photoControllerCreate>>,
  TError,
  { data: PhotoCreateRequest },
  TContext
> => {
  const mutationKey = ['photoControllerCreate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof photoControllerCreate>>,
    { data: PhotoCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return photoControllerCreate(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PhotoControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof photoControllerCreate>>>;
export type PhotoControllerCreateMutationBody = PhotoCreateRequest;
export type PhotoControllerCreateMutationError = unknown;

export const usePhotoControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof photoControllerCreate>>,
      TError,
      { data: PhotoCreateRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof photoControllerCreate>>,
  TError,
  { data: PhotoCreateRequest },
  TContext
> => {
  const mutationOptions = getPhotoControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export type photoControllerUploadResponse201 = {
  data: FileResponse;
  status: 201;
};

export type photoControllerUploadResponseSuccess = photoControllerUploadResponse201 & {
  headers: Headers;
};
export const getPhotoControllerUploadUrl = () => {
  return `http://localhost:4000/api/v1/photos/image`;
};

export const photoControllerUpload = async (
  photoControllerUploadBody: PhotoControllerUploadBody,
  options?: RequestInit,
): Promise<photoControllerUploadResponseSuccess> => {
  const formData = new FormData();
  formData.append(`image`, photoControllerUploadBody.image);

  const res = await fetch(getPhotoControllerUploadUrl(), {
    credentials: 'include',
    ...options,
    method: 'POST',
    body: formData,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: photoControllerUploadResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as photoControllerUploadResponseSuccess;
};

export const getPhotoControllerUploadMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof photoControllerUpload>>,
    TError,
    { data: PhotoControllerUploadBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof photoControllerUpload>>,
  TError,
  { data: PhotoControllerUploadBody },
  TContext
> => {
  const mutationKey = ['photoControllerUpload'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof photoControllerUpload>>,
    { data: PhotoControllerUploadBody }
  > = (props) => {
    const { data } = props ?? {};

    return photoControllerUpload(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PhotoControllerUploadMutationResult = NonNullable<Awaited<ReturnType<typeof photoControllerUpload>>>;
export type PhotoControllerUploadMutationBody = PhotoControllerUploadBody;
export type PhotoControllerUploadMutationError = unknown;

export const usePhotoControllerUpload = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof photoControllerUpload>>,
      TError,
      { data: PhotoControllerUploadBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof photoControllerUpload>>,
  TError,
  { data: PhotoControllerUploadBody },
  TContext
> => {
  const mutationOptions = getPhotoControllerUploadMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
