/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useQuery, useSuspenseInfiniteQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import type {
  PhotoResponse,
  ProfileControllerAnimals200,
  ProfileControllerPhotos200,
  ProfileControllerPhotosParams,
  ProfileResponse,
} from './index.schemas';

export type profileControllerReadResponse200 = {
  data: ProfileResponse;
  status: 200;
};

export type profileControllerReadResponseSuccess = profileControllerReadResponse200 & {
  headers: Headers;
};
export const getProfileControllerReadUrl = (username: string) => {
  return `http://localhost:4000/api/v1/profiles/${username}`;
};

export const profileControllerRead = async (
  username: string,
  options?: RequestInit,
): Promise<profileControllerReadResponseSuccess> => {
  const res = await fetch(getProfileControllerReadUrl(username), {
    credentials: 'include',
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: profileControllerReadResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as profileControllerReadResponseSuccess;
};

export const getProfileControllerReadInfiniteQueryKey = (username?: string) => {
  return ['infinite', `http://localhost:4000/api/v1/profiles/${username}`] as const;
};

export const getProfileControllerReadQueryKey = (username?: string) => {
  return [`http://localhost:4000/api/v1/profiles/${username}`] as const;
};

export const getProfileControllerReadInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerRead>>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileControllerReadInfiniteQueryKey(username);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerRead>>> = ({ signal }) =>
    profileControllerRead(username, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!username, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof profileControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileControllerReadInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof profileControllerRead>>>;
export type ProfileControllerReadInfiniteQueryError = unknown;

export function useProfileControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerRead>>>,
  TError = unknown,
>(
  username: string,
  options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerRead>>,
          TError,
          Awaited<ReturnType<typeof profileControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerRead>>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerRead>>,
          TError,
          Awaited<ReturnType<typeof profileControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerRead>>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerRead>>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileControllerReadInfiniteQueryOptions(username, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchProfileControllerReadInfiniteQuery = async <
  TData = Awaited<ReturnType<typeof profileControllerRead>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  username: string,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getProfileControllerReadInfiniteQueryOptions(username, options);

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
};

export const getProfileControllerReadQueryOptions = <
  TData = Awaited<ReturnType<typeof profileControllerRead>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileControllerReadQueryKey(username);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerRead>>> = ({ signal }) =>
    profileControllerRead(username, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!username, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof profileControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileControllerReadQueryResult = NonNullable<Awaited<ReturnType<typeof profileControllerRead>>>;
export type ProfileControllerReadQueryError = unknown;

export function useProfileControllerRead<TData = Awaited<ReturnType<typeof profileControllerRead>>, TError = unknown>(
  username: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerRead>>,
          TError,
          Awaited<ReturnType<typeof profileControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerRead<TData = Awaited<ReturnType<typeof profileControllerRead>>, TError = unknown>(
  username: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerRead>>,
          TError,
          Awaited<ReturnType<typeof profileControllerRead>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerRead<TData = Awaited<ReturnType<typeof profileControllerRead>>, TError = unknown>(
  username: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileControllerRead<TData = Awaited<ReturnType<typeof profileControllerRead>>, TError = unknown>(
  username: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileControllerReadQueryOptions(username, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchProfileControllerReadQuery = async <
  TData = Awaited<ReturnType<typeof profileControllerRead>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  username: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getProfileControllerReadQueryOptions(username, options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getProfileControllerReadSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof profileControllerRead>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileControllerReadQueryKey(username);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerRead>>> = ({ signal }) =>
    profileControllerRead(username, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof profileControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileControllerReadSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof profileControllerRead>>>;
export type ProfileControllerReadSuspenseQueryError = unknown;

export function useProfileControllerReadSuspense<
  TData = Awaited<ReturnType<typeof profileControllerRead>>,
  TError = unknown,
>(
  username: string,
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerReadSuspense<
  TData = Awaited<ReturnType<typeof profileControllerRead>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerReadSuspense<
  TData = Awaited<ReturnType<typeof profileControllerRead>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileControllerReadSuspense<
  TData = Awaited<ReturnType<typeof profileControllerRead>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileControllerReadSuspenseQueryOptions(username, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getProfileControllerReadSuspenseInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerRead>>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileControllerReadInfiniteQueryKey(username);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerRead>>> = ({ signal }) =>
    profileControllerRead(username, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseInfiniteQueryOptions<
    Awaited<ReturnType<typeof profileControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileControllerReadSuspenseInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileControllerRead>>
>;
export type ProfileControllerReadSuspenseInfiniteQueryError = unknown;

export function useProfileControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerRead>>>,
  TError = unknown,
>(
  username: string,
  options: {
    query: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerRead>>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerRead>>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerRead>>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerRead>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileControllerReadSuspenseInfiniteQueryOptions(username, options);

  const query = useSuspenseInfiniteQuery(queryOptions, queryClient) as UseSuspenseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type profileControllerAnimalsResponse200 = {
  data: ProfileControllerAnimals200;
  status: 200;
};

export type profileControllerAnimalsResponseSuccess = profileControllerAnimalsResponse200 & {
  headers: Headers;
};
export const getProfileControllerAnimalsUrl = (username: string) => {
  return `http://localhost:4000/api/v1/profiles/${username}/animals`;
};

export const profileControllerAnimals = async (
  username: string,
  options?: RequestInit,
): Promise<profileControllerAnimalsResponseSuccess> => {
  const res = await fetch(getProfileControllerAnimalsUrl(username), {
    credentials: 'include',
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: profileControllerAnimalsResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as profileControllerAnimalsResponseSuccess;
};

export const getProfileControllerAnimalsInfiniteQueryKey = (username?: string) => {
  return ['infinite', `http://localhost:4000/api/v1/profiles/${username}/animals`] as const;
};

export const getProfileControllerAnimalsQueryKey = (username?: string) => {
  return [`http://localhost:4000/api/v1/profiles/${username}/animals`] as const;
};

export const getProfileControllerAnimalsInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerAnimals>>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileControllerAnimalsInfiniteQueryKey(username);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerAnimals>>> = ({ signal }) =>
    profileControllerAnimals(username, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!username, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof profileControllerAnimals>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileControllerAnimalsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileControllerAnimals>>
>;
export type ProfileControllerAnimalsInfiniteQueryError = unknown;

export function useProfileControllerAnimalsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerAnimals>>>,
  TError = unknown,
>(
  username: string,
  options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerAnimals>>,
          TError,
          Awaited<ReturnType<typeof profileControllerAnimals>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerAnimalsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerAnimals>>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerAnimals>>,
          TError,
          Awaited<ReturnType<typeof profileControllerAnimals>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerAnimalsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerAnimals>>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileControllerAnimalsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerAnimals>>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileControllerAnimalsInfiniteQueryOptions(username, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchProfileControllerAnimalsInfiniteQuery = async <
  TData = Awaited<ReturnType<typeof profileControllerAnimals>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  username: string,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getProfileControllerAnimalsInfiniteQueryOptions(username, options);

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
};

export const getProfileControllerAnimalsQueryOptions = <
  TData = Awaited<ReturnType<typeof profileControllerAnimals>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileControllerAnimalsQueryKey(username);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerAnimals>>> = ({ signal }) =>
    profileControllerAnimals(username, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!username, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof profileControllerAnimals>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileControllerAnimalsQueryResult = NonNullable<Awaited<ReturnType<typeof profileControllerAnimals>>>;
export type ProfileControllerAnimalsQueryError = unknown;

export function useProfileControllerAnimals<
  TData = Awaited<ReturnType<typeof profileControllerAnimals>>,
  TError = unknown,
>(
  username: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerAnimals>>,
          TError,
          Awaited<ReturnType<typeof profileControllerAnimals>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerAnimals<
  TData = Awaited<ReturnType<typeof profileControllerAnimals>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerAnimals>>,
          TError,
          Awaited<ReturnType<typeof profileControllerAnimals>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerAnimals<
  TData = Awaited<ReturnType<typeof profileControllerAnimals>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileControllerAnimals<
  TData = Awaited<ReturnType<typeof profileControllerAnimals>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileControllerAnimalsQueryOptions(username, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchProfileControllerAnimalsQuery = async <
  TData = Awaited<ReturnType<typeof profileControllerAnimals>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  username: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getProfileControllerAnimalsQueryOptions(username, options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getProfileControllerAnimalsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof profileControllerAnimals>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileControllerAnimalsQueryKey(username);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerAnimals>>> = ({ signal }) =>
    profileControllerAnimals(username, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof profileControllerAnimals>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileControllerAnimalsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileControllerAnimals>>
>;
export type ProfileControllerAnimalsSuspenseQueryError = unknown;

export function useProfileControllerAnimalsSuspense<
  TData = Awaited<ReturnType<typeof profileControllerAnimals>>,
  TError = unknown,
>(
  username: string,
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerAnimalsSuspense<
  TData = Awaited<ReturnType<typeof profileControllerAnimals>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerAnimalsSuspense<
  TData = Awaited<ReturnType<typeof profileControllerAnimals>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileControllerAnimalsSuspense<
  TData = Awaited<ReturnType<typeof profileControllerAnimals>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileControllerAnimalsSuspenseQueryOptions(username, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getProfileControllerAnimalsSuspenseInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerAnimals>>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileControllerAnimalsInfiniteQueryKey(username);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerAnimals>>> = ({ signal }) =>
    profileControllerAnimals(username, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseInfiniteQueryOptions<
    Awaited<ReturnType<typeof profileControllerAnimals>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileControllerAnimalsSuspenseInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileControllerAnimals>>
>;
export type ProfileControllerAnimalsSuspenseInfiniteQueryError = unknown;

export function useProfileControllerAnimalsSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerAnimals>>>,
  TError = unknown,
>(
  username: string,
  options: {
    query: Partial<
      UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerAnimalsSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerAnimals>>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerAnimalsSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerAnimals>>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileControllerAnimalsSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerAnimals>>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerAnimals>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileControllerAnimalsSuspenseInfiniteQueryOptions(username, options);

  const query = useSuspenseInfiniteQuery(queryOptions, queryClient) as UseSuspenseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type profileControllerPhotosResponse200 = {
  data: ProfileControllerPhotos200;
  status: 200;
};

export type profileControllerPhotosResponseSuccess = profileControllerPhotosResponse200 & {
  headers: Headers;
};
export const getProfileControllerPhotosUrl = (username: string, params?: ProfileControllerPhotosParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://localhost:4000/api/v1/profiles/${username}/photos?${stringifiedParams}`
    : `http://localhost:4000/api/v1/profiles/${username}/photos`;
};

export const profileControllerPhotos = async (
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: RequestInit,
): Promise<profileControllerPhotosResponseSuccess> => {
  const res = await fetch(getProfileControllerPhotosUrl(username, params), {
    credentials: 'include',
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: profileControllerPhotosResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as profileControllerPhotosResponseSuccess;
};

export const getProfileControllerPhotosInfiniteQueryKey = (
  username?: string,
  params?: ProfileControllerPhotosParams,
) => {
  return ['infinite', `http://localhost:4000/api/v1/profiles/${username}/photos`, ...(params ? [params] : [])] as const;
};

export const getProfileControllerPhotosQueryKey = (username?: string, params?: ProfileControllerPhotosParams) => {
  return [`http://localhost:4000/api/v1/profiles/${username}/photos`, ...(params ? [params] : [])] as const;
};

export const getProfileControllerPhotosInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhotos>>, ProfileControllerPhotosParams['cursor']>,
  TError = unknown,
>(
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof profileControllerPhotos>>,
        TError,
        TData,
        QueryKey,
        ProfileControllerPhotosParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileControllerPhotosInfiniteQueryKey(username, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof profileControllerPhotos>>,
    QueryKey,
    ProfileControllerPhotosParams['cursor']
  > = ({ signal, pageParam }) =>
    profileControllerPhotos(
      username,
      { ...params, cursor: pageParam || params?.['cursor'] },
      { signal, ...fetchOptions },
    );

  return { queryKey, queryFn, enabled: !!username, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof profileControllerPhotos>>,
    TError,
    TData,
    QueryKey,
    ProfileControllerPhotosParams['cursor']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileControllerPhotosInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileControllerPhotos>>
>;
export type ProfileControllerPhotosInfiniteQueryError = unknown;

export function useProfileControllerPhotosInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhotos>>, ProfileControllerPhotosParams['cursor']>,
  TError = unknown,
>(
  username: string,
  params: undefined | ProfileControllerPhotosParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof profileControllerPhotos>>,
        TError,
        TData,
        QueryKey,
        ProfileControllerPhotosParams['cursor']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerPhotos>>,
          TError,
          Awaited<ReturnType<typeof profileControllerPhotos>>,
          QueryKey
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerPhotosInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhotos>>, ProfileControllerPhotosParams['cursor']>,
  TError = unknown,
>(
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof profileControllerPhotos>>,
        TError,
        TData,
        QueryKey,
        ProfileControllerPhotosParams['cursor']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerPhotos>>,
          TError,
          Awaited<ReturnType<typeof profileControllerPhotos>>,
          QueryKey
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerPhotosInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhotos>>, ProfileControllerPhotosParams['cursor']>,
  TError = unknown,
>(
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof profileControllerPhotos>>,
        TError,
        TData,
        QueryKey,
        ProfileControllerPhotosParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileControllerPhotosInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhotos>>, ProfileControllerPhotosParams['cursor']>,
  TError = unknown,
>(
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof profileControllerPhotos>>,
        TError,
        TData,
        QueryKey,
        ProfileControllerPhotosParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileControllerPhotosInfiniteQueryOptions(username, params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchProfileControllerPhotosInfiniteQuery = async <
  TData = Awaited<ReturnType<typeof profileControllerPhotos>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof profileControllerPhotos>>,
        TError,
        TData,
        QueryKey,
        ProfileControllerPhotosParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getProfileControllerPhotosInfiniteQueryOptions(username, params, options);

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
};

export const getProfileControllerPhotosQueryOptions = <
  TData = Awaited<ReturnType<typeof profileControllerPhotos>>,
  TError = unknown,
>(
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerPhotos>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileControllerPhotosQueryKey(username, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerPhotos>>> = ({ signal }) =>
    profileControllerPhotos(username, params, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!username, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof profileControllerPhotos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileControllerPhotosQueryResult = NonNullable<Awaited<ReturnType<typeof profileControllerPhotos>>>;
export type ProfileControllerPhotosQueryError = unknown;

export function useProfileControllerPhotos<
  TData = Awaited<ReturnType<typeof profileControllerPhotos>>,
  TError = unknown,
>(
  username: string,
  params: undefined | ProfileControllerPhotosParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerPhotos>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerPhotos>>,
          TError,
          Awaited<ReturnType<typeof profileControllerPhotos>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerPhotos<
  TData = Awaited<ReturnType<typeof profileControllerPhotos>>,
  TError = unknown,
>(
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerPhotos>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerPhotos>>,
          TError,
          Awaited<ReturnType<typeof profileControllerPhotos>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerPhotos<
  TData = Awaited<ReturnType<typeof profileControllerPhotos>>,
  TError = unknown,
>(
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerPhotos>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileControllerPhotos<
  TData = Awaited<ReturnType<typeof profileControllerPhotos>>,
  TError = unknown,
>(
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerPhotos>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileControllerPhotosQueryOptions(username, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchProfileControllerPhotosQuery = async <
  TData = Awaited<ReturnType<typeof profileControllerPhotos>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerPhotos>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getProfileControllerPhotosQueryOptions(username, params, options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getProfileControllerPhotosSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof profileControllerPhotos>>,
  TError = unknown,
>(
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerPhotos>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileControllerPhotosQueryKey(username, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerPhotos>>> = ({ signal }) =>
    profileControllerPhotos(username, params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof profileControllerPhotos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileControllerPhotosSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileControllerPhotos>>
>;
export type ProfileControllerPhotosSuspenseQueryError = unknown;

export function useProfileControllerPhotosSuspense<
  TData = Awaited<ReturnType<typeof profileControllerPhotos>>,
  TError = unknown,
>(
  username: string,
  params: undefined | ProfileControllerPhotosParams,
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerPhotos>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerPhotosSuspense<
  TData = Awaited<ReturnType<typeof profileControllerPhotos>>,
  TError = unknown,
>(
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerPhotos>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerPhotosSuspense<
  TData = Awaited<ReturnType<typeof profileControllerPhotos>>,
  TError = unknown,
>(
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerPhotos>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileControllerPhotosSuspense<
  TData = Awaited<ReturnType<typeof profileControllerPhotos>>,
  TError = unknown,
>(
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerPhotos>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileControllerPhotosSuspenseQueryOptions(username, params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getProfileControllerPhotosSuspenseInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhotos>>, ProfileControllerPhotosParams['cursor']>,
  TError = unknown,
>(
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof profileControllerPhotos>>,
        TError,
        TData,
        QueryKey,
        ProfileControllerPhotosParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileControllerPhotosInfiniteQueryKey(username, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof profileControllerPhotos>>,
    QueryKey,
    ProfileControllerPhotosParams['cursor']
  > = ({ signal, pageParam }) =>
    profileControllerPhotos(
      username,
      { ...params, cursor: pageParam || params?.['cursor'] },
      { signal, ...fetchOptions },
    );

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseInfiniteQueryOptions<
    Awaited<ReturnType<typeof profileControllerPhotos>>,
    TError,
    TData,
    QueryKey,
    ProfileControllerPhotosParams['cursor']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileControllerPhotosSuspenseInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileControllerPhotos>>
>;
export type ProfileControllerPhotosSuspenseInfiniteQueryError = unknown;

export function useProfileControllerPhotosSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhotos>>, ProfileControllerPhotosParams['cursor']>,
  TError = unknown,
>(
  username: string,
  params: undefined | ProfileControllerPhotosParams,
  options: {
    query: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof profileControllerPhotos>>,
        TError,
        TData,
        QueryKey,
        ProfileControllerPhotosParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerPhotosSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhotos>>, ProfileControllerPhotosParams['cursor']>,
  TError = unknown,
>(
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof profileControllerPhotos>>,
        TError,
        TData,
        QueryKey,
        ProfileControllerPhotosParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerPhotosSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhotos>>, ProfileControllerPhotosParams['cursor']>,
  TError = unknown,
>(
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof profileControllerPhotos>>,
        TError,
        TData,
        QueryKey,
        ProfileControllerPhotosParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileControllerPhotosSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhotos>>, ProfileControllerPhotosParams['cursor']>,
  TError = unknown,
>(
  username: string,
  params?: ProfileControllerPhotosParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof profileControllerPhotos>>,
        TError,
        TData,
        QueryKey,
        ProfileControllerPhotosParams['cursor']
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileControllerPhotosSuspenseInfiniteQueryOptions(username, params, options);

  const query = useSuspenseInfiniteQuery(queryOptions, queryClient) as UseSuspenseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type profileControllerPhotoResponse200 = {
  data: PhotoResponse;
  status: 200;
};

export type profileControllerPhotoResponseSuccess = profileControllerPhotoResponse200 & {
  headers: Headers;
};
export const getProfileControllerPhotoUrl = (username: string, id: number) => {
  return `http://localhost:4000/api/v1/profiles/${username}/photos/${id}`;
};

export const profileControllerPhoto = async (
  username: string,
  id: number,
  options?: RequestInit,
): Promise<profileControllerPhotoResponseSuccess> => {
  const res = await fetch(getProfileControllerPhotoUrl(username, id), {
    credentials: 'include',
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: globalThis.Error & { info?: any; status?: number } = new globalThis.Error();
    const data = body ? JSON.parse(body) : {};
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: profileControllerPhotoResponseSuccess['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as profileControllerPhotoResponseSuccess;
};

export const getProfileControllerPhotoInfiniteQueryKey = (username?: string, id?: number) => {
  return ['infinite', `http://localhost:4000/api/v1/profiles/${username}/photos/${id}`] as const;
};

export const getProfileControllerPhotoQueryKey = (username?: string, id?: number) => {
  return [`http://localhost:4000/api/v1/profiles/${username}/photos/${id}`] as const;
};

export const getProfileControllerPhotoInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhoto>>>,
  TError = unknown,
>(
  username: string,
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileControllerPhotoInfiniteQueryKey(username, id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerPhoto>>> = ({ signal }) =>
    profileControllerPhoto(username, id, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!(username && id), ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof profileControllerPhoto>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileControllerPhotoInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof profileControllerPhoto>>>;
export type ProfileControllerPhotoInfiniteQueryError = unknown;

export function useProfileControllerPhotoInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhoto>>>,
  TError = unknown,
>(
  username: string,
  id: number,
  options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerPhoto>>,
          TError,
          Awaited<ReturnType<typeof profileControllerPhoto>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerPhotoInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhoto>>>,
  TError = unknown,
>(
  username: string,
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerPhoto>>,
          TError,
          Awaited<ReturnType<typeof profileControllerPhoto>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerPhotoInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhoto>>>,
  TError = unknown,
>(
  username: string,
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileControllerPhotoInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhoto>>>,
  TError = unknown,
>(
  username: string,
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileControllerPhotoInfiniteQueryOptions(username, id, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchProfileControllerPhotoInfiniteQuery = async <
  TData = Awaited<ReturnType<typeof profileControllerPhoto>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  username: string,
  id: number,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getProfileControllerPhotoInfiniteQueryOptions(username, id, options);

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
};

export const getProfileControllerPhotoQueryOptions = <
  TData = Awaited<ReturnType<typeof profileControllerPhoto>>,
  TError = unknown,
>(
  username: string,
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileControllerPhotoQueryKey(username, id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerPhoto>>> = ({ signal }) =>
    profileControllerPhoto(username, id, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!(username && id), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof profileControllerPhoto>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileControllerPhotoQueryResult = NonNullable<Awaited<ReturnType<typeof profileControllerPhoto>>>;
export type ProfileControllerPhotoQueryError = unknown;

export function useProfileControllerPhoto<TData = Awaited<ReturnType<typeof profileControllerPhoto>>, TError = unknown>(
  username: string,
  id: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerPhoto>>,
          TError,
          Awaited<ReturnType<typeof profileControllerPhoto>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerPhoto<TData = Awaited<ReturnType<typeof profileControllerPhoto>>, TError = unknown>(
  username: string,
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileControllerPhoto>>,
          TError,
          Awaited<ReturnType<typeof profileControllerPhoto>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerPhoto<TData = Awaited<ReturnType<typeof profileControllerPhoto>>, TError = unknown>(
  username: string,
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileControllerPhoto<TData = Awaited<ReturnType<typeof profileControllerPhoto>>, TError = unknown>(
  username: string,
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileControllerPhotoQueryOptions(username, id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchProfileControllerPhotoQuery = async <
  TData = Awaited<ReturnType<typeof profileControllerPhoto>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  username: string,
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
): Promise<QueryClient> => {
  const queryOptions = getProfileControllerPhotoQueryOptions(username, id, options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getProfileControllerPhotoSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof profileControllerPhoto>>,
  TError = unknown,
>(
  username: string,
  id: number,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileControllerPhotoQueryKey(username, id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerPhoto>>> = ({ signal }) =>
    profileControllerPhoto(username, id, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof profileControllerPhoto>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileControllerPhotoSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof profileControllerPhoto>>>;
export type ProfileControllerPhotoSuspenseQueryError = unknown;

export function useProfileControllerPhotoSuspense<
  TData = Awaited<ReturnType<typeof profileControllerPhoto>>,
  TError = unknown,
>(
  username: string,
  id: number,
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerPhotoSuspense<
  TData = Awaited<ReturnType<typeof profileControllerPhoto>>,
  TError = unknown,
>(
  username: string,
  id: number,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerPhotoSuspense<
  TData = Awaited<ReturnType<typeof profileControllerPhoto>>,
  TError = unknown,
>(
  username: string,
  id: number,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileControllerPhotoSuspense<
  TData = Awaited<ReturnType<typeof profileControllerPhoto>>,
  TError = unknown,
>(
  username: string,
  id: number,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileControllerPhotoSuspenseQueryOptions(username, id, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getProfileControllerPhotoSuspenseInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhoto>>>,
  TError = unknown,
>(
  username: string,
  id: number,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileControllerPhotoInfiniteQueryKey(username, id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileControllerPhoto>>> = ({ signal }) =>
    profileControllerPhoto(username, id, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseInfiniteQueryOptions<
    Awaited<ReturnType<typeof profileControllerPhoto>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileControllerPhotoSuspenseInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileControllerPhoto>>
>;
export type ProfileControllerPhotoSuspenseInfiniteQueryError = unknown;

export function useProfileControllerPhotoSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhoto>>>,
  TError = unknown,
>(
  username: string,
  id: number,
  options: {
    query: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerPhotoSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhoto>>>,
  TError = unknown,
>(
  username: string,
  id: number,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileControllerPhotoSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhoto>>>,
  TError = unknown,
>(
  username: string,
  id: number,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileControllerPhotoSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof profileControllerPhoto>>>,
  TError = unknown,
>(
  username: string,
  id: number,
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof profileControllerPhoto>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileControllerPhotoSuspenseInfiniteQueryOptions(username, id, options);

  const query = useSuspenseInfiniteQuery(queryOptions, queryClient) as UseSuspenseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
