/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseInfiniteQuery,
  useSuspenseQuery,
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import type { FileResponse, UserControllerThumbnailBody, UserResponse, UserUpdateRequest } from './index.schemas';

import { customFetch } from './mutator/custom-fetch';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type userControllerReadResponse200 = {
  data: UserResponse;
  status: 200;
};

export type userControllerReadResponseSuccess = userControllerReadResponse200 & {
  headers: Headers;
};
export type userControllerReadResponse = userControllerReadResponseSuccess;

export const getUserControllerReadUrl = () => {
  return `/api/v1/users`;
};

export const userControllerRead = async (options?: RequestInit): Promise<userControllerReadResponse> => {
  return customFetch<userControllerReadResponse>(getUserControllerReadUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getUserControllerReadInfiniteQueryKey = () => {
  return ['infinite', `/api/v1/users`] as const;
};

export const getUserControllerReadQueryKey = () => {
  return [`/api/v1/users`] as const;
};

export const getUserControllerReadInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof userControllerRead>>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerReadInfiniteQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerRead>>> = ({ signal }) =>
    userControllerRead({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof userControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerReadInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerRead>>>;
export type UserControllerReadInfiniteQueryError = unknown;

export function useUserControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof userControllerRead>>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerRead>>,
          TError,
          Awaited<ReturnType<typeof userControllerRead>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof userControllerRead>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerRead>>,
          TError,
          Awaited<ReturnType<typeof userControllerRead>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof userControllerRead>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useUserControllerReadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof userControllerRead>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUserControllerReadInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchUserControllerReadInfiniteQuery = async <
  TData = Awaited<ReturnType<typeof userControllerRead>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
): Promise<QueryClient> => {
  const queryOptions = getUserControllerReadInfiniteQueryOptions(options);

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
};

export const getUserControllerReadQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerRead>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerReadQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerRead>>> = ({ signal }) =>
    userControllerRead({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerReadQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerRead>>>;
export type UserControllerReadQueryError = unknown;

export function useUserControllerRead<TData = Awaited<ReturnType<typeof userControllerRead>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerRead>>,
          TError,
          Awaited<ReturnType<typeof userControllerRead>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerRead<TData = Awaited<ReturnType<typeof userControllerRead>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerRead>>,
          TError,
          Awaited<ReturnType<typeof userControllerRead>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerRead<TData = Awaited<ReturnType<typeof userControllerRead>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useUserControllerRead<TData = Awaited<ReturnType<typeof userControllerRead>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUserControllerReadQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const prefetchUserControllerReadQuery = async <
  TData = Awaited<ReturnType<typeof userControllerRead>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
): Promise<QueryClient> => {
  const queryOptions = getUserControllerReadQueryOptions(options);

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
};

export const getUserControllerReadSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerRead>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerReadQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerRead>>> = ({ signal }) =>
    userControllerRead({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof userControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerReadSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerRead>>>;
export type UserControllerReadSuspenseQueryError = unknown;

export function useUserControllerReadSuspense<TData = Awaited<ReturnType<typeof userControllerRead>>, TError = unknown>(
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerReadSuspense<TData = Awaited<ReturnType<typeof userControllerRead>>, TError = unknown>(
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerReadSuspense<TData = Awaited<ReturnType<typeof userControllerRead>>, TError = unknown>(
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useUserControllerReadSuspense<TData = Awaited<ReturnType<typeof userControllerRead>>, TError = unknown>(
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUserControllerReadSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getUserControllerReadSuspenseInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof userControllerRead>>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerReadInfiniteQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerRead>>> = ({ signal }) =>
    userControllerRead({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseInfiniteQueryOptions<
    Awaited<ReturnType<typeof userControllerRead>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerReadSuspenseInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerRead>>>;
export type UserControllerReadSuspenseInfiniteQueryError = unknown;

export function useUserControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof userControllerRead>>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof userControllerRead>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof userControllerRead>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useUserControllerReadSuspenseInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof userControllerRead>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof userControllerRead>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUserControllerReadSuspenseInfiniteQueryOptions(options);

  const query = useSuspenseInfiniteQuery(queryOptions, queryClient) as UseSuspenseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type userControllerUpdateResponse200 = {
  data: UserResponse;
  status: 200;
};

export type userControllerUpdateResponseSuccess = userControllerUpdateResponse200 & {
  headers: Headers;
};
export type userControllerUpdateResponse = userControllerUpdateResponseSuccess;

export const getUserControllerUpdateUrl = () => {
  return `/api/v1/users`;
};

export const userControllerUpdate = async (
  userUpdateRequest: UserUpdateRequest,
  options?: RequestInit,
): Promise<userControllerUpdateResponse> => {
  return customFetch<userControllerUpdateResponse>(getUserControllerUpdateUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userUpdateRequest),
  });
};

export const getUserControllerUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerUpdate>>,
    TError,
    { data: UserUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerUpdate>>,
  TError,
  { data: UserUpdateRequest },
  TContext
> => {
  const mutationKey = ['userControllerUpdate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerUpdate>>, { data: UserUpdateRequest }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return userControllerUpdate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerUpdate>>>;
export type UserControllerUpdateMutationBody = UserUpdateRequest;
export type UserControllerUpdateMutationError = unknown;

export const useUserControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerUpdate>>,
      TError,
      { data: UserUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerUpdate>>,
  TError,
  { data: UserUpdateRequest },
  TContext
> => {
  const mutationOptions = getUserControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export type userControllerDeleteResponse200 = {
  data: UserResponse;
  status: 200;
};

export type userControllerDeleteResponseSuccess = userControllerDeleteResponse200 & {
  headers: Headers;
};
export type userControllerDeleteResponse = userControllerDeleteResponseSuccess;

export const getUserControllerDeleteUrl = () => {
  return `/api/v1/users`;
};

export const userControllerDelete = async (options?: RequestInit): Promise<userControllerDeleteResponse> => {
  return customFetch<userControllerDeleteResponse>(getUserControllerDeleteUrl(), {
    ...options,
    method: 'DELETE',
  });
};

export const getUserControllerDeleteMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof userControllerDelete>>, TError, void, TContext>;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof userControllerDelete>>, TError, void, TContext> => {
  const mutationKey = ['userControllerDelete'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerDelete>>, void> = () => {
    return userControllerDelete(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerDelete>>>;

export type UserControllerDeleteMutationError = unknown;

export const useUserControllerDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof userControllerDelete>>, TError, void, TContext>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof userControllerDelete>>, TError, void, TContext> => {
  const mutationOptions = getUserControllerDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export type userControllerThumbnailResponse201 = {
  data: FileResponse;
  status: 201;
};

export type userControllerThumbnailResponseSuccess = userControllerThumbnailResponse201 & {
  headers: Headers;
};
export type userControllerThumbnailResponse = userControllerThumbnailResponseSuccess;

export const getUserControllerThumbnailUrl = () => {
  return `/api/v1/users/thumbnail`;
};

export const userControllerThumbnail = async (
  userControllerThumbnailBody: UserControllerThumbnailBody,
  options?: RequestInit,
): Promise<userControllerThumbnailResponse> => {
  const formData = new FormData();
  formData.append(`thumbnail`, userControllerThumbnailBody.thumbnail);

  return customFetch<userControllerThumbnailResponse>(getUserControllerThumbnailUrl(), {
    ...options,
    method: 'POST',
    body: formData,
  });
};

export const getUserControllerThumbnailMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerThumbnail>>,
    TError,
    { data: UserControllerThumbnailBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerThumbnail>>,
  TError,
  { data: UserControllerThumbnailBody },
  TContext
> => {
  const mutationKey = ['userControllerThumbnail'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerThumbnail>>,
    { data: UserControllerThumbnailBody }
  > = (props) => {
    const { data } = props ?? {};

    return userControllerThumbnail(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerThumbnailMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerThumbnail>>>;
export type UserControllerThumbnailMutationBody = UserControllerThumbnailBody;
export type UserControllerThumbnailMutationError = unknown;

export const useUserControllerThumbnail = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerThumbnail>>,
      TError,
      { data: UserControllerThumbnailBody },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerThumbnail>>,
  TError,
  { data: UserControllerThumbnailBody },
  TContext
> => {
  const mutationOptions = getUserControllerThumbnailMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
